-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity simulation_top_gvt_tracker_top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    lpcore_lvt_stream_0_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    lpcore_lvt_stream_0_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_lvt_stream_0_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_lvt_stream_0_empty_n : IN STD_LOGIC;
    lpcore_lvt_stream_0_read : OUT STD_LOGIC;
    lpcore_lvt_stream_1_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    lpcore_lvt_stream_1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_lvt_stream_1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_lvt_stream_1_empty_n : IN STD_LOGIC;
    lpcore_lvt_stream_1_read : OUT STD_LOGIC;
    gvt_stream8_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    gvt_stream8_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    gvt_stream8_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    gvt_stream8_full_n : IN STD_LOGIC;
    gvt_stream8_write : OUT STD_LOGIC );
end;


architecture behav of simulation_top_gvt_tracker_top is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal gvt_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal lvt_arr_V_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal lvt_arr_V_ce0 : STD_LOGIC;
    signal lvt_arr_V_we0 : STD_LOGIC;
    signal lvt_arr_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal lvt_arr_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal lpcore_lvt_stream_0_blk_n : STD_LOGIC;
    signal tmp_nbreadreq_fu_58_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal lpcore_lvt_stream_1_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_s_nbreadreq_fu_79_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal gvt_stream8_blk_n : STD_LOGIC;
    signal tmp_reg_291 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1081_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal tmp_s_reg_301 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1081_1_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal reg_200 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_start : STD_LOGIC;
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_done : STD_LOGIC;
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_idle : STD_LOGIC;
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_ready : STD_LOGIC;
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_p_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_p_out_ap_vld : STD_LOGIC;
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_lvt_arr_V_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_lvt_arr_V_ce0 : STD_LOGIC;
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_start : STD_LOGIC;
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_done : STD_LOGIC;
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_idle : STD_LOGIC;
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_ready : STD_LOGIC;
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_p_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_p_out_ap_vld : STD_LOGIC;
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_lvt_arr_V_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_lvt_arr_V_ce0 : STD_LOGIC;
    signal ap_phi_mux_gvt_V_flag_1_phi_fu_119_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal gvt_V_flag_1_reg_115 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op33_write_state6 : BOOLEAN;
    signal ap_block_state6 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal ap_phi_mux_gvt_V_new_1_phi_fu_135_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal gvt_V_new_1_reg_131 : STD_LOGIC_VECTOR (31 downto 0);
    signal gvt_V_loc_1_reg_145 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_gvt_V_flag_3_phi_fu_160_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal gvt_V_flag_3_reg_157 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op53_write_state11 : BOOLEAN;
    signal ap_block_state11 : BOOLEAN;
    signal ap_phi_mux_gvt_V_new_3_phi_fu_174_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal gvt_V_new_3_reg_171 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal zext_ln587_fu_225_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_9_fu_257_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal tmp_lp_id_V_fu_210_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_lp_id_V_3_fu_242_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component simulation_top_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        min_val_V : IN STD_LOGIC_VECTOR (31 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        lvt_arr_V_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        lvt_arr_V_ce0 : OUT STD_LOGIC;
        lvt_arr_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component simulation_top_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        min_val_V_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        lvt_arr_V_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        lvt_arr_V_ce0 : OUT STD_LOGIC;
        lvt_arr_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component simulation_top_gvt_tracker_top_lvt_arr_V_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    lvt_arr_V_U : component simulation_top_gvt_tracker_top_lvt_arr_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 4,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => lvt_arr_V_address0,
        ce0 => lvt_arr_V_ce0,
        we0 => lvt_arr_V_we0,
        d0 => lvt_arr_V_d0,
        q0 => lvt_arr_V_q0);

    grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184 : component simulation_top_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_start,
        ap_done => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_done,
        ap_idle => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_idle,
        ap_ready => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_ready,
        min_val_V => reg_200,
        p_out => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_p_out,
        p_out_ap_vld => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_p_out_ap_vld,
        lvt_arr_V_address0 => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_lvt_arr_V_address0,
        lvt_arr_V_ce0 => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_lvt_arr_V_ce0,
        lvt_arr_V_q0 => lvt_arr_V_q0);

    grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192 : component simulation_top_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_start,
        ap_done => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_done,
        ap_idle => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_idle,
        ap_ready => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_ready,
        min_val_V_2 => reg_200,
        p_out => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_p_out,
        p_out_ap_vld => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_p_out_ap_vld,
        lvt_arr_V_address0 => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_lvt_arr_V_address0,
        lvt_arr_V_ce0 => grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_lvt_arr_V_ce0,
        lvt_arr_V_q0 => lvt_arr_V_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op53_write_state11 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_ready = ap_const_logic_1)) then 
                    grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_ready = ap_const_logic_1)) then 
                    grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    gvt_V_flag_1_reg_115_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_0_empty_n = ap_const_logic_0)))) and (tmp_nbreadreq_fu_58_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (icmp_ln1081_fu_237_p2 = ap_const_lv1_0) and (tmp_reg_291 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
                gvt_V_flag_1_reg_115 <= ap_const_lv1_0;
            elsif ((not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (icmp_ln1081_fu_237_p2 = ap_const_lv1_1) and (tmp_reg_291 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                gvt_V_flag_1_reg_115 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    gvt_V_flag_3_reg_157_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op53_write_state11 = ap_const_boolean_1))) and (icmp_ln1081_1_fu_267_p2 = ap_const_lv1_0) and (tmp_s_reg_301 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                gvt_V_flag_3_reg_157 <= gvt_V_flag_1_reg_115;
            elsif ((not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                gvt_V_flag_3_reg_157 <= ap_phi_mux_gvt_V_flag_1_phi_fu_119_p6;
            elsif ((not(((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op53_write_state11 = ap_const_boolean_1))) and (icmp_ln1081_1_fu_267_p2 = ap_const_lv1_1) and (tmp_s_reg_301 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                gvt_V_flag_3_reg_157 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    gvt_V_loc_1_reg_145_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_0_empty_n = ap_const_logic_0)))) and (tmp_nbreadreq_fu_58_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (icmp_ln1081_fu_237_p2 = ap_const_lv1_0) and (tmp_reg_291 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
                gvt_V_loc_1_reg_145 <= gvt_V;
            elsif ((not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (icmp_ln1081_fu_237_p2 = ap_const_lv1_1) and (tmp_reg_291 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                gvt_V_loc_1_reg_145 <= grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_p_out;
            end if; 
        end if;
    end process;

    gvt_V_new_3_reg_171_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op53_write_state11 = ap_const_boolean_1))) and (icmp_ln1081_1_fu_267_p2 = ap_const_lv1_0) and (tmp_s_reg_301 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                gvt_V_new_3_reg_171 <= gvt_V_new_1_reg_131;
            elsif ((not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                gvt_V_new_3_reg_171 <= ap_phi_mux_gvt_V_new_1_phi_fu_135_p6;
            elsif ((not(((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op53_write_state11 = ap_const_boolean_1))) and (icmp_ln1081_1_fu_267_p2 = ap_const_lv1_1) and (tmp_s_reg_301 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                gvt_V_new_3_reg_171 <= grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_p_out;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op53_write_state11 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state11) and (ap_phi_mux_gvt_V_flag_3_phi_fu_160_p6 = ap_const_lv1_1))) then
                gvt_V <= ap_phi_mux_gvt_V_new_3_phi_fu_174_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (icmp_ln1081_fu_237_p2 = ap_const_lv1_1) and (tmp_reg_291 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or (not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (icmp_ln1081_fu_237_p2 = ap_const_lv1_0) and (tmp_reg_291 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then
                gvt_V_new_1_reg_131 <= grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_p_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state3))) then
                reg_200 <= lvt_arr_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                tmp_reg_291 <= tmp_nbreadreq_fu_58_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                tmp_s_reg_301 <= tmp_s_nbreadreq_fu_79_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, lpcore_lvt_stream_0_empty_n, lpcore_lvt_stream_1_empty_n, gvt_stream8_full_n, tmp_nbreadreq_fu_58_p3, ap_CS_fsm_state6, tmp_s_nbreadreq_fu_79_p3, ap_CS_fsm_state11, grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_done, grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_done, ap_predicate_op33_write_state6, ap_predicate_op53_write_state11, ap_CS_fsm_state5, ap_CS_fsm_state10)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_0_empty_n = ap_const_logic_0)))) and (tmp_nbreadreq_fu_58_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_0_empty_n = ap_const_logic_0)))) and (tmp_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if ((not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                elsif ((not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                if ((not(((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op53_write_state11 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_done)
    begin
        if ((grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state11_blk_assign_proc : process(gvt_stream8_full_n, ap_predicate_op53_write_state11)
    begin
        if (((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op53_write_state11 = ap_const_boolean_1))) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, lpcore_lvt_stream_0_empty_n, tmp_nbreadreq_fu_58_p3)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_0_empty_n = ap_const_logic_0)))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_done)
    begin
        if ((grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(lpcore_lvt_stream_1_empty_n, gvt_stream8_full_n, tmp_s_nbreadreq_fu_79_p3, ap_predicate_op33_write_state6)
    begin
        if ((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, lpcore_lvt_stream_0_empty_n, tmp_nbreadreq_fu_58_p3)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_0_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state11_assign_proc : process(gvt_stream8_full_n, ap_predicate_op53_write_state11)
    begin
                ap_block_state11 <= ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op53_write_state11 = ap_const_boolean_1));
    end process;


    ap_block_state6_assign_proc : process(lpcore_lvt_stream_1_empty_n, gvt_stream8_full_n, tmp_s_nbreadreq_fu_79_p3, ap_predicate_op33_write_state6)
    begin
                ap_block_state6 <= (((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, gvt_stream8_full_n, ap_CS_fsm_state11, ap_predicate_op53_write_state11)
    begin
        if ((not(((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op53_write_state11 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_gvt_V_flag_1_phi_fu_119_p6_assign_proc : process(ap_CS_fsm_state6, tmp_reg_291, icmp_ln1081_fu_237_p2, gvt_V_flag_1_reg_115)
    begin
        if (((tmp_reg_291 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
            if ((icmp_ln1081_fu_237_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_gvt_V_flag_1_phi_fu_119_p6 <= ap_const_lv1_0;
            elsif ((icmp_ln1081_fu_237_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_gvt_V_flag_1_phi_fu_119_p6 <= ap_const_lv1_1;
            else 
                ap_phi_mux_gvt_V_flag_1_phi_fu_119_p6 <= gvt_V_flag_1_reg_115;
            end if;
        else 
            ap_phi_mux_gvt_V_flag_1_phi_fu_119_p6 <= gvt_V_flag_1_reg_115;
        end if; 
    end process;


    ap_phi_mux_gvt_V_flag_3_phi_fu_160_p6_assign_proc : process(ap_CS_fsm_state11, tmp_s_reg_301, icmp_ln1081_1_fu_267_p2, gvt_V_flag_1_reg_115, gvt_V_flag_3_reg_157)
    begin
        if (((tmp_s_reg_301 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
            if ((icmp_ln1081_1_fu_267_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_gvt_V_flag_3_phi_fu_160_p6 <= gvt_V_flag_1_reg_115;
            elsif ((icmp_ln1081_1_fu_267_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_gvt_V_flag_3_phi_fu_160_p6 <= ap_const_lv1_1;
            else 
                ap_phi_mux_gvt_V_flag_3_phi_fu_160_p6 <= gvt_V_flag_3_reg_157;
            end if;
        else 
            ap_phi_mux_gvt_V_flag_3_phi_fu_160_p6 <= gvt_V_flag_3_reg_157;
        end if; 
    end process;


    ap_phi_mux_gvt_V_new_1_phi_fu_135_p6_assign_proc : process(ap_CS_fsm_state6, tmp_reg_291, icmp_ln1081_fu_237_p2, grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_p_out, gvt_V_new_1_reg_131)
    begin
        if ((((icmp_ln1081_fu_237_p2 = ap_const_lv1_1) and (tmp_reg_291 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((icmp_ln1081_fu_237_p2 = ap_const_lv1_0) and (tmp_reg_291 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            ap_phi_mux_gvt_V_new_1_phi_fu_135_p6 <= grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_p_out;
        else 
            ap_phi_mux_gvt_V_new_1_phi_fu_135_p6 <= gvt_V_new_1_reg_131;
        end if; 
    end process;


    ap_phi_mux_gvt_V_new_3_phi_fu_174_p6_assign_proc : process(ap_CS_fsm_state11, tmp_s_reg_301, icmp_ln1081_1_fu_267_p2, grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_p_out, gvt_V_new_1_reg_131, gvt_V_new_3_reg_171)
    begin
        if (((tmp_s_reg_301 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
            if ((icmp_ln1081_1_fu_267_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_gvt_V_new_3_phi_fu_174_p6 <= gvt_V_new_1_reg_131;
            elsif ((icmp_ln1081_1_fu_267_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_gvt_V_new_3_phi_fu_174_p6 <= grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_p_out;
            else 
                ap_phi_mux_gvt_V_new_3_phi_fu_174_p6 <= gvt_V_new_3_reg_171;
            end if;
        else 
            ap_phi_mux_gvt_V_new_3_phi_fu_174_p6 <= gvt_V_new_3_reg_171;
        end if; 
    end process;


    ap_predicate_op33_write_state6_assign_proc : process(tmp_reg_291, icmp_ln1081_fu_237_p2)
    begin
                ap_predicate_op33_write_state6 <= ((icmp_ln1081_fu_237_p2 = ap_const_lv1_1) and (tmp_reg_291 = ap_const_lv1_1));
    end process;


    ap_predicate_op53_write_state11_assign_proc : process(tmp_s_reg_301, icmp_ln1081_1_fu_267_p2)
    begin
                ap_predicate_op53_write_state11 <= ((icmp_ln1081_1_fu_267_p2 = ap_const_lv1_1) and (tmp_s_reg_301 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(gvt_stream8_full_n, ap_CS_fsm_state11, ap_predicate_op53_write_state11)
    begin
        if ((not(((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op53_write_state11 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_start <= grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_ap_start_reg;
    grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_start <= grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_ap_start_reg;

    gvt_stream8_blk_n_assign_proc : process(gvt_stream8_full_n, ap_CS_fsm_state6, tmp_reg_291, icmp_ln1081_fu_237_p2, ap_CS_fsm_state11, tmp_s_reg_301, icmp_ln1081_1_fu_267_p2)
    begin
        if ((((icmp_ln1081_1_fu_267_p2 = ap_const_lv1_1) and (tmp_s_reg_301 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((icmp_ln1081_fu_237_p2 = ap_const_lv1_1) and (tmp_reg_291 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            gvt_stream8_blk_n <= gvt_stream8_full_n;
        else 
            gvt_stream8_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    gvt_stream8_din_assign_proc : process(lpcore_lvt_stream_1_empty_n, gvt_stream8_full_n, ap_CS_fsm_state6, tmp_s_nbreadreq_fu_79_p3, ap_CS_fsm_state11, grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_p_out, grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_p_out, ap_predicate_op33_write_state6, ap_predicate_op53_write_state11)
    begin
        if ((not(((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op53_write_state11 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state11) and (ap_predicate_op53_write_state11 = ap_const_boolean_1))) then 
            gvt_stream8_din <= grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_p_out;
        elsif ((not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op33_write_state6 = ap_const_boolean_1))) then 
            gvt_stream8_din <= grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_p_out;
        else 
            gvt_stream8_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    gvt_stream8_write_assign_proc : process(lpcore_lvt_stream_1_empty_n, gvt_stream8_full_n, ap_CS_fsm_state6, tmp_s_nbreadreq_fu_79_p3, ap_CS_fsm_state11, ap_predicate_op33_write_state6, ap_predicate_op53_write_state11)
    begin
        if (((not(((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op53_write_state11 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state11) and (ap_predicate_op53_write_state11 = ap_const_boolean_1)) or (not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) then 
            gvt_stream8_write <= ap_const_logic_1;
        else 
            gvt_stream8_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1081_1_fu_267_p2 <= "1" when (signed(grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_p_out) > signed(gvt_V_loc_1_reg_145)) else "0";
    icmp_ln1081_fu_237_p2 <= "1" when (signed(grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_p_out) > signed(gvt_V)) else "0";

    lpcore_lvt_stream_0_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_lvt_stream_0_empty_n, tmp_nbreadreq_fu_58_p3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (tmp_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            lpcore_lvt_stream_0_blk_n <= lpcore_lvt_stream_0_empty_n;
        else 
            lpcore_lvt_stream_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lpcore_lvt_stream_0_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_lvt_stream_0_empty_n, tmp_nbreadreq_fu_58_p3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_0_empty_n = ap_const_logic_0)))) and (tmp_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            lpcore_lvt_stream_0_read <= ap_const_logic_1;
        else 
            lpcore_lvt_stream_0_read <= ap_const_logic_0;
        end if; 
    end process;


    lpcore_lvt_stream_1_blk_n_assign_proc : process(lpcore_lvt_stream_1_empty_n, ap_CS_fsm_state6, tmp_s_nbreadreq_fu_79_p3)
    begin
        if (((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            lpcore_lvt_stream_1_blk_n <= lpcore_lvt_stream_1_empty_n;
        else 
            lpcore_lvt_stream_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lpcore_lvt_stream_1_read_assign_proc : process(lpcore_lvt_stream_1_empty_n, gvt_stream8_full_n, ap_CS_fsm_state6, tmp_s_nbreadreq_fu_79_p3, ap_predicate_op33_write_state6)
    begin
        if ((not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            lpcore_lvt_stream_1_read <= ap_const_logic_1;
        else 
            lpcore_lvt_stream_1_read <= ap_const_logic_0;
        end if; 
    end process;


    lvt_arr_V_address0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state6, grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_lvt_arr_V_address0, grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_lvt_arr_V_address0, ap_CS_fsm_state5, ap_CS_fsm_state10, zext_ln587_fu_225_p1, zext_ln587_9_fu_257_p1, ap_CS_fsm_state2, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            lvt_arr_V_address0 <= zext_ln587_9_fu_257_p1(2 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            lvt_arr_V_address0 <= ap_const_lv2_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            lvt_arr_V_address0 <= zext_ln587_fu_225_p1(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            lvt_arr_V_address0 <= grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_lvt_arr_V_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            lvt_arr_V_address0 <= grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_lvt_arr_V_address0;
        else 
            lvt_arr_V_address0 <= "XX";
        end if; 
    end process;


    lvt_arr_V_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_lvt_stream_0_empty_n, lpcore_lvt_stream_1_empty_n, gvt_stream8_full_n, tmp_nbreadreq_fu_58_p3, ap_CS_fsm_state6, tmp_s_nbreadreq_fu_79_p3, grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_lvt_arr_V_ce0, grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_lvt_arr_V_ce0, ap_predicate_op33_write_state6, ap_CS_fsm_state5, ap_CS_fsm_state10, ap_CS_fsm_state2, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2) or (not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_0_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            lvt_arr_V_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            lvt_arr_V_ce0 <= grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_11_fu_192_lvt_arr_V_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            lvt_arr_V_ce0 <= grp_gvt_tracker_top_Pipeline_VITIS_LOOP_34_1_fu_184_lvt_arr_V_ce0;
        else 
            lvt_arr_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    lvt_arr_V_d0_assign_proc : process(ap_CS_fsm_state1, lpcore_lvt_stream_0_dout, lpcore_lvt_stream_1_dout, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            lvt_arr_V_d0 <= lpcore_lvt_stream_1_dout(47 downto 16);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            lvt_arr_V_d0 <= lpcore_lvt_stream_0_dout(47 downto 16);
        else 
            lvt_arr_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    lvt_arr_V_we0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_lvt_stream_0_empty_n, lpcore_lvt_stream_1_empty_n, gvt_stream8_full_n, tmp_nbreadreq_fu_58_p3, ap_CS_fsm_state6, tmp_s_nbreadreq_fu_79_p3, ap_predicate_op33_write_state6)
    begin
        if (((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_0_empty_n = ap_const_logic_0)))) and (tmp_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not((((tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (lpcore_lvt_stream_1_empty_n = ap_const_logic_0)) or ((gvt_stream8_full_n = ap_const_logic_0) and (ap_predicate_op33_write_state6 = ap_const_boolean_1)))) and (tmp_s_nbreadreq_fu_79_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            lvt_arr_V_we0 <= ap_const_logic_1;
        else 
            lvt_arr_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_lp_id_V_3_fu_242_p1 <= lpcore_lvt_stream_1_dout(2 - 1 downto 0);
    tmp_lp_id_V_fu_210_p1 <= lpcore_lvt_stream_0_dout(2 - 1 downto 0);
    tmp_nbreadreq_fu_58_p3 <= (0=>(lpcore_lvt_stream_0_empty_n), others=>'-');
    tmp_s_nbreadreq_fu_79_p3 <= (0=>(lpcore_lvt_stream_1_empty_n), others=>'-');
    zext_ln587_9_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_lp_id_V_3_fu_242_p1),64));
    zext_ln587_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_lp_id_V_fu_210_p1),64));
end behav;
