-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity simulation_top_lpcore_kernel_1_s is
port (
    lpcore_init_event_stream_1_dout : IN STD_LOGIC_VECTOR (128 downto 0);
    lpcore_init_event_stream_1_empty_n : IN STD_LOGIC;
    lpcore_init_event_stream_1_read : OUT STD_LOGIC;
    lpcore_event_queue_full_stream_1_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    lpcore_event_queue_full_stream_1_full_n : IN STD_LOGIC;
    lpcore_event_queue_full_stream_1_write : OUT STD_LOGIC;
    lpcore_anti_message_stream_1_dout : IN STD_LOGIC_VECTOR (128 downto 0);
    lpcore_anti_message_stream_1_empty_n : IN STD_LOGIC;
    lpcore_anti_message_stream_1_read : OUT STD_LOGIC;
    lpcore_enqueue_event_stream_1_dout : IN STD_LOGIC_VECTOR (128 downto 0);
    lpcore_enqueue_event_stream_1_empty_n : IN STD_LOGIC;
    lpcore_enqueue_event_stream_1_read : OUT STD_LOGIC;
    lpcore_lvt_stream_1_din : OUT STD_LOGIC_VECTOR (47 downto 0);
    lpcore_lvt_stream_1_full_n : IN STD_LOGIC;
    lpcore_lvt_stream_1_write : OUT STD_LOGIC;
    lpcore_output_event_stream_1_din : OUT STD_LOGIC_VECTOR (128 downto 0);
    lpcore_output_event_stream_1_full_n : IN STD_LOGIC;
    lpcore_output_event_stream_1_write : OUT STD_LOGIC;
    lpcore_cancellation_unit_output_stream_1_din : OUT STD_LOGIC_VECTOR (128 downto 0);
    lpcore_cancellation_unit_output_stream_1_full_n : IN STD_LOGIC;
    lpcore_cancellation_unit_output_stream_1_write : OUT STD_LOGIC;
    lpcore_commit_time_stream_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    lpcore_commit_time_stream_1_empty_n : IN STD_LOGIC;
    lpcore_commit_time_stream_1_read : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_ready : OUT STD_LOGIC );
end;


architecture behav of simulation_top_lpcore_kernel_1_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal lpcore_control_top_1_U0_causality_violation_stream_read : STD_LOGIC;
    signal lpcore_control_top_1_U0_event_queue_rollback_info_stream_din : STD_LOGIC_VECTOR (47 downto 0);
    signal lpcore_control_top_1_U0_event_queue_rollback_info_stream_write : STD_LOGIC;
    signal lpcore_control_top_1_U0_state_buffer_rollback_info_stream_din : STD_LOGIC_VECTOR (47 downto 0);
    signal lpcore_control_top_1_U0_state_buffer_rollback_info_stream_write : STD_LOGIC;
    signal lpcore_control_top_1_U0_cancellation_unit_rollback_info_stream_din : STD_LOGIC_VECTOR (47 downto 0);
    signal lpcore_control_top_1_U0_cancellation_unit_rollback_info_stream_write : STD_LOGIC;
    signal lpcore_control_top_1_U0_lpcore_commit_time_stream_1_read : STD_LOGIC;
    signal lpcore_control_top_1_U0_event_queue_commit_time_stream15_din : STD_LOGIC_VECTOR (31 downto 0);
    signal lpcore_control_top_1_U0_event_queue_commit_time_stream15_write : STD_LOGIC;
    signal lpcore_control_top_1_U0_state_buffer_commit_time_stream16_din : STD_LOGIC_VECTOR (31 downto 0);
    signal lpcore_control_top_1_U0_state_buffer_commit_time_stream16_write : STD_LOGIC;
    signal lpcore_control_top_1_U0_cancellation_unit_commit_time_stream17_din : STD_LOGIC_VECTOR (31 downto 0);
    signal lpcore_control_top_1_U0_cancellation_unit_commit_time_stream17_write : STD_LOGIC;
    signal lpcore_control_top_1_U0_ap_ready : STD_LOGIC;
    signal event_queue_top_1_U0_ap_start : STD_LOGIC;
    signal event_queue_top_1_U0_ap_done : STD_LOGIC;
    signal event_queue_top_1_U0_ap_continue : STD_LOGIC;
    signal event_queue_top_1_U0_ap_idle : STD_LOGIC;
    signal event_queue_top_1_U0_ap_ready : STD_LOGIC;
    signal event_queue_top_1_U0_lpcore_init_event_stream_1_read : STD_LOGIC;
    signal event_queue_top_1_U0_lpcore_event_queue_full_stream_1_din : STD_LOGIC_VECTOR (0 downto 0);
    signal event_queue_top_1_U0_lpcore_event_queue_full_stream_1_write : STD_LOGIC;
    signal event_queue_top_1_U0_event_queue_rollback_info_stream_read : STD_LOGIC;
    signal event_queue_top_1_U0_lpcore_anti_message_stream_1_read : STD_LOGIC;
    signal event_queue_top_1_U0_lpcore_enqueue_event_stream_1_read : STD_LOGIC;
    signal event_queue_top_1_U0_event_queue_commit_time_stream15_read : STD_LOGIC;
    signal event_queue_top_1_U0_issued_event_stream_din : STD_LOGIC_VECTOR (128 downto 0);
    signal event_queue_top_1_U0_issued_event_stream_write : STD_LOGIC;
    signal event_queue_top_1_U0_causality_violation_stream_din : STD_LOGIC_VECTOR (47 downto 0);
    signal event_queue_top_1_U0_causality_violation_stream_write : STD_LOGIC;
    signal state_buffer_top_1_U0_ap_start : STD_LOGIC;
    signal state_buffer_top_1_U0_ap_done : STD_LOGIC;
    signal state_buffer_top_1_U0_ap_continue : STD_LOGIC;
    signal state_buffer_top_1_U0_ap_idle : STD_LOGIC;
    signal state_buffer_top_1_U0_ap_ready : STD_LOGIC;
    signal state_buffer_top_1_U0_state_buffer_rollback_info_stream_read : STD_LOGIC;
    signal state_buffer_top_1_U0_state_buffer_commit_time_stream16_read : STD_LOGIC;
    signal state_buffer_top_1_U0_state_buffer_input_stream_read : STD_LOGIC;
    signal state_buffer_top_1_U0_issued_event_stream_read : STD_LOGIC;
    signal state_buffer_top_1_U0_event_processor_input_stream_din : STD_LOGIC_VECTOR (208 downto 0);
    signal state_buffer_top_1_U0_event_processor_input_stream_write : STD_LOGIC;
    signal event_processor_top_1_U0_ap_start : STD_LOGIC;
    signal event_processor_top_1_U0_ap_done : STD_LOGIC;
    signal event_processor_top_1_U0_ap_continue : STD_LOGIC;
    signal event_processor_top_1_U0_ap_idle : STD_LOGIC;
    signal event_processor_top_1_U0_ap_ready : STD_LOGIC;
    signal event_processor_top_1_U0_event_processor_input_stream_read : STD_LOGIC;
    signal event_processor_top_1_U0_state_buffer_input_stream_din : STD_LOGIC_VECTOR (79 downto 0);
    signal event_processor_top_1_U0_state_buffer_input_stream_write : STD_LOGIC;
    signal event_processor_top_1_U0_lpcore_lvt_stream_1_din : STD_LOGIC_VECTOR (47 downto 0);
    signal event_processor_top_1_U0_lpcore_lvt_stream_1_write : STD_LOGIC;
    signal event_processor_top_1_U0_lpcore_output_event_stream_1_din : STD_LOGIC_VECTOR (128 downto 0);
    signal event_processor_top_1_U0_lpcore_output_event_stream_1_write : STD_LOGIC;
    signal event_processor_top_1_U0_cancellation_unit_input_stream_din : STD_LOGIC_VECTOR (128 downto 0);
    signal event_processor_top_1_U0_cancellation_unit_input_stream_write : STD_LOGIC;
    signal cancellation_unit_top_1_U0_ap_start : STD_LOGIC;
    signal cancellation_unit_top_1_U0_ap_done : STD_LOGIC;
    signal cancellation_unit_top_1_U0_ap_continue : STD_LOGIC;
    signal cancellation_unit_top_1_U0_ap_idle : STD_LOGIC;
    signal cancellation_unit_top_1_U0_ap_ready : STD_LOGIC;
    signal cancellation_unit_top_1_U0_cancellation_unit_rollback_info_stream_read : STD_LOGIC;
    signal cancellation_unit_top_1_U0_cancellation_unit_commit_time_stream17_read : STD_LOGIC;
    signal cancellation_unit_top_1_U0_cancellation_unit_input_stream_read : STD_LOGIC;
    signal cancellation_unit_top_1_U0_lpcore_cancellation_unit_output_stream_1_din : STD_LOGIC_VECTOR (128 downto 0);
    signal cancellation_unit_top_1_U0_lpcore_cancellation_unit_output_stream_1_write : STD_LOGIC;
    signal causality_violation_stream_full_n : STD_LOGIC;
    signal causality_violation_stream_dout : STD_LOGIC_VECTOR (47 downto 0);
    signal causality_violation_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal causality_violation_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal causality_violation_stream_empty_n : STD_LOGIC;
    signal event_queue_rollback_info_stream_full_n : STD_LOGIC;
    signal event_queue_rollback_info_stream_dout : STD_LOGIC_VECTOR (47 downto 0);
    signal event_queue_rollback_info_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal event_queue_rollback_info_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal event_queue_rollback_info_stream_empty_n : STD_LOGIC;
    signal state_buffer_rollback_info_stream_full_n : STD_LOGIC;
    signal state_buffer_rollback_info_stream_dout : STD_LOGIC_VECTOR (47 downto 0);
    signal state_buffer_rollback_info_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal state_buffer_rollback_info_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal state_buffer_rollback_info_stream_empty_n : STD_LOGIC;
    signal cancellation_unit_rollback_info_stream_full_n : STD_LOGIC;
    signal cancellation_unit_rollback_info_stream_dout : STD_LOGIC_VECTOR (47 downto 0);
    signal cancellation_unit_rollback_info_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal cancellation_unit_rollback_info_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal cancellation_unit_rollback_info_stream_empty_n : STD_LOGIC;
    signal event_queue_commit_time_stream_full_n : STD_LOGIC;
    signal event_queue_commit_time_stream_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal event_queue_commit_time_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal event_queue_commit_time_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal event_queue_commit_time_stream_empty_n : STD_LOGIC;
    signal state_buffer_commit_time_stream_full_n : STD_LOGIC;
    signal state_buffer_commit_time_stream_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal state_buffer_commit_time_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal state_buffer_commit_time_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal state_buffer_commit_time_stream_empty_n : STD_LOGIC;
    signal cancellation_unit_commit_time_stream_full_n : STD_LOGIC;
    signal cancellation_unit_commit_time_stream_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal cancellation_unit_commit_time_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal cancellation_unit_commit_time_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal cancellation_unit_commit_time_stream_empty_n : STD_LOGIC;
    signal issued_event_stream_full_n : STD_LOGIC;
    signal issued_event_stream_dout : STD_LOGIC_VECTOR (128 downto 0);
    signal issued_event_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal issued_event_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal issued_event_stream_empty_n : STD_LOGIC;
    signal state_buffer_input_stream_full_n : STD_LOGIC;
    signal state_buffer_input_stream_dout : STD_LOGIC_VECTOR (79 downto 0);
    signal state_buffer_input_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal state_buffer_input_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal state_buffer_input_stream_empty_n : STD_LOGIC;
    signal event_processor_input_stream_full_n : STD_LOGIC;
    signal event_processor_input_stream_dout : STD_LOGIC_VECTOR (208 downto 0);
    signal event_processor_input_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal event_processor_input_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal event_processor_input_stream_empty_n : STD_LOGIC;
    signal cancellation_unit_input_stream_full_n : STD_LOGIC;
    signal cancellation_unit_input_stream_dout : STD_LOGIC_VECTOR (128 downto 0);
    signal cancellation_unit_input_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal cancellation_unit_input_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal cancellation_unit_input_stream_empty_n : STD_LOGIC;

    component simulation_top_lpcore_control_top_1_s IS
    port (
        causality_violation_stream_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        causality_violation_stream_empty_n : IN STD_LOGIC;
        causality_violation_stream_read : OUT STD_LOGIC;
        event_queue_rollback_info_stream_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        event_queue_rollback_info_stream_full_n : IN STD_LOGIC;
        event_queue_rollback_info_stream_write : OUT STD_LOGIC;
        state_buffer_rollback_info_stream_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        state_buffer_rollback_info_stream_full_n : IN STD_LOGIC;
        state_buffer_rollback_info_stream_write : OUT STD_LOGIC;
        cancellation_unit_rollback_info_stream_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        cancellation_unit_rollback_info_stream_full_n : IN STD_LOGIC;
        cancellation_unit_rollback_info_stream_write : OUT STD_LOGIC;
        lpcore_commit_time_stream_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        lpcore_commit_time_stream_1_empty_n : IN STD_LOGIC;
        lpcore_commit_time_stream_1_read : OUT STD_LOGIC;
        event_queue_commit_time_stream15_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        event_queue_commit_time_stream15_full_n : IN STD_LOGIC;
        event_queue_commit_time_stream15_write : OUT STD_LOGIC;
        state_buffer_commit_time_stream16_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        state_buffer_commit_time_stream16_full_n : IN STD_LOGIC;
        state_buffer_commit_time_stream16_write : OUT STD_LOGIC;
        cancellation_unit_commit_time_stream17_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        cancellation_unit_commit_time_stream17_full_n : IN STD_LOGIC;
        cancellation_unit_commit_time_stream17_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC );
    end component;


    component simulation_top_event_queue_top_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        lpcore_init_event_stream_1_dout : IN STD_LOGIC_VECTOR (128 downto 0);
        lpcore_init_event_stream_1_empty_n : IN STD_LOGIC;
        lpcore_init_event_stream_1_read : OUT STD_LOGIC;
        lpcore_event_queue_full_stream_1_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        lpcore_event_queue_full_stream_1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        lpcore_event_queue_full_stream_1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        lpcore_event_queue_full_stream_1_full_n : IN STD_LOGIC;
        lpcore_event_queue_full_stream_1_write : OUT STD_LOGIC;
        event_queue_rollback_info_stream_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        event_queue_rollback_info_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        event_queue_rollback_info_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        event_queue_rollback_info_stream_empty_n : IN STD_LOGIC;
        event_queue_rollback_info_stream_read : OUT STD_LOGIC;
        lpcore_anti_message_stream_1_dout : IN STD_LOGIC_VECTOR (128 downto 0);
        lpcore_anti_message_stream_1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        lpcore_anti_message_stream_1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        lpcore_anti_message_stream_1_empty_n : IN STD_LOGIC;
        lpcore_anti_message_stream_1_read : OUT STD_LOGIC;
        lpcore_enqueue_event_stream_1_dout : IN STD_LOGIC_VECTOR (128 downto 0);
        lpcore_enqueue_event_stream_1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        lpcore_enqueue_event_stream_1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        lpcore_enqueue_event_stream_1_empty_n : IN STD_LOGIC;
        lpcore_enqueue_event_stream_1_read : OUT STD_LOGIC;
        event_queue_commit_time_stream15_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        event_queue_commit_time_stream15_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        event_queue_commit_time_stream15_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        event_queue_commit_time_stream15_empty_n : IN STD_LOGIC;
        event_queue_commit_time_stream15_read : OUT STD_LOGIC;
        issued_event_stream_din : OUT STD_LOGIC_VECTOR (128 downto 0);
        issued_event_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        issued_event_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        issued_event_stream_full_n : IN STD_LOGIC;
        issued_event_stream_write : OUT STD_LOGIC;
        causality_violation_stream_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        causality_violation_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        causality_violation_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        causality_violation_stream_full_n : IN STD_LOGIC;
        causality_violation_stream_write : OUT STD_LOGIC );
    end component;


    component simulation_top_state_buffer_top_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        state_buffer_rollback_info_stream_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        state_buffer_rollback_info_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        state_buffer_rollback_info_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        state_buffer_rollback_info_stream_empty_n : IN STD_LOGIC;
        state_buffer_rollback_info_stream_read : OUT STD_LOGIC;
        state_buffer_commit_time_stream16_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        state_buffer_commit_time_stream16_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        state_buffer_commit_time_stream16_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        state_buffer_commit_time_stream16_empty_n : IN STD_LOGIC;
        state_buffer_commit_time_stream16_read : OUT STD_LOGIC;
        state_buffer_input_stream_dout : IN STD_LOGIC_VECTOR (79 downto 0);
        state_buffer_input_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        state_buffer_input_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        state_buffer_input_stream_empty_n : IN STD_LOGIC;
        state_buffer_input_stream_read : OUT STD_LOGIC;
        issued_event_stream_dout : IN STD_LOGIC_VECTOR (128 downto 0);
        issued_event_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        issued_event_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        issued_event_stream_empty_n : IN STD_LOGIC;
        issued_event_stream_read : OUT STD_LOGIC;
        event_processor_input_stream_din : OUT STD_LOGIC_VECTOR (208 downto 0);
        event_processor_input_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        event_processor_input_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        event_processor_input_stream_full_n : IN STD_LOGIC;
        event_processor_input_stream_write : OUT STD_LOGIC );
    end component;


    component simulation_top_event_processor_top_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        event_processor_input_stream_dout : IN STD_LOGIC_VECTOR (208 downto 0);
        event_processor_input_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        event_processor_input_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        event_processor_input_stream_empty_n : IN STD_LOGIC;
        event_processor_input_stream_read : OUT STD_LOGIC;
        state_buffer_input_stream_din : OUT STD_LOGIC_VECTOR (79 downto 0);
        state_buffer_input_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        state_buffer_input_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        state_buffer_input_stream_full_n : IN STD_LOGIC;
        state_buffer_input_stream_write : OUT STD_LOGIC;
        lpcore_lvt_stream_1_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        lpcore_lvt_stream_1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        lpcore_lvt_stream_1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        lpcore_lvt_stream_1_full_n : IN STD_LOGIC;
        lpcore_lvt_stream_1_write : OUT STD_LOGIC;
        lpcore_output_event_stream_1_din : OUT STD_LOGIC_VECTOR (128 downto 0);
        lpcore_output_event_stream_1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        lpcore_output_event_stream_1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        lpcore_output_event_stream_1_full_n : IN STD_LOGIC;
        lpcore_output_event_stream_1_write : OUT STD_LOGIC;
        cancellation_unit_input_stream_din : OUT STD_LOGIC_VECTOR (128 downto 0);
        cancellation_unit_input_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        cancellation_unit_input_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        cancellation_unit_input_stream_full_n : IN STD_LOGIC;
        cancellation_unit_input_stream_write : OUT STD_LOGIC );
    end component;


    component simulation_top_cancellation_unit_top_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        cancellation_unit_rollback_info_stream_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        cancellation_unit_rollback_info_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        cancellation_unit_rollback_info_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        cancellation_unit_rollback_info_stream_empty_n : IN STD_LOGIC;
        cancellation_unit_rollback_info_stream_read : OUT STD_LOGIC;
        cancellation_unit_commit_time_stream17_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        cancellation_unit_commit_time_stream17_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        cancellation_unit_commit_time_stream17_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        cancellation_unit_commit_time_stream17_empty_n : IN STD_LOGIC;
        cancellation_unit_commit_time_stream17_read : OUT STD_LOGIC;
        cancellation_unit_input_stream_dout : IN STD_LOGIC_VECTOR (128 downto 0);
        cancellation_unit_input_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        cancellation_unit_input_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        cancellation_unit_input_stream_empty_n : IN STD_LOGIC;
        cancellation_unit_input_stream_read : OUT STD_LOGIC;
        lpcore_cancellation_unit_output_stream_1_din : OUT STD_LOGIC_VECTOR (128 downto 0);
        lpcore_cancellation_unit_output_stream_1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        lpcore_cancellation_unit_output_stream_1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        lpcore_cancellation_unit_output_stream_1_full_n : IN STD_LOGIC;
        lpcore_cancellation_unit_output_stream_1_write : OUT STD_LOGIC );
    end component;


    component simulation_top_fifo_w48_d2_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (47 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (47 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component simulation_top_fifo_w32_d2_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component simulation_top_fifo_w129_d2_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (128 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (128 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component simulation_top_fifo_w80_d2_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (79 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (79 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component simulation_top_fifo_w209_d2_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (208 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (208 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    lpcore_control_top_1_U0 : component simulation_top_lpcore_control_top_1_s
    port map (
        causality_violation_stream_dout => causality_violation_stream_dout,
        causality_violation_stream_empty_n => causality_violation_stream_empty_n,
        causality_violation_stream_read => lpcore_control_top_1_U0_causality_violation_stream_read,
        event_queue_rollback_info_stream_din => lpcore_control_top_1_U0_event_queue_rollback_info_stream_din,
        event_queue_rollback_info_stream_full_n => event_queue_rollback_info_stream_full_n,
        event_queue_rollback_info_stream_write => lpcore_control_top_1_U0_event_queue_rollback_info_stream_write,
        state_buffer_rollback_info_stream_din => lpcore_control_top_1_U0_state_buffer_rollback_info_stream_din,
        state_buffer_rollback_info_stream_full_n => state_buffer_rollback_info_stream_full_n,
        state_buffer_rollback_info_stream_write => lpcore_control_top_1_U0_state_buffer_rollback_info_stream_write,
        cancellation_unit_rollback_info_stream_din => lpcore_control_top_1_U0_cancellation_unit_rollback_info_stream_din,
        cancellation_unit_rollback_info_stream_full_n => cancellation_unit_rollback_info_stream_full_n,
        cancellation_unit_rollback_info_stream_write => lpcore_control_top_1_U0_cancellation_unit_rollback_info_stream_write,
        lpcore_commit_time_stream_1_dout => lpcore_commit_time_stream_1_dout,
        lpcore_commit_time_stream_1_empty_n => lpcore_commit_time_stream_1_empty_n,
        lpcore_commit_time_stream_1_read => lpcore_control_top_1_U0_lpcore_commit_time_stream_1_read,
        event_queue_commit_time_stream15_din => lpcore_control_top_1_U0_event_queue_commit_time_stream15_din,
        event_queue_commit_time_stream15_full_n => event_queue_commit_time_stream_full_n,
        event_queue_commit_time_stream15_write => lpcore_control_top_1_U0_event_queue_commit_time_stream15_write,
        state_buffer_commit_time_stream16_din => lpcore_control_top_1_U0_state_buffer_commit_time_stream16_din,
        state_buffer_commit_time_stream16_full_n => state_buffer_commit_time_stream_full_n,
        state_buffer_commit_time_stream16_write => lpcore_control_top_1_U0_state_buffer_commit_time_stream16_write,
        cancellation_unit_commit_time_stream17_din => lpcore_control_top_1_U0_cancellation_unit_commit_time_stream17_din,
        cancellation_unit_commit_time_stream17_full_n => cancellation_unit_commit_time_stream_full_n,
        cancellation_unit_commit_time_stream17_write => lpcore_control_top_1_U0_cancellation_unit_commit_time_stream17_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_ready => lpcore_control_top_1_U0_ap_ready);

    event_queue_top_1_U0 : component simulation_top_event_queue_top_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => event_queue_top_1_U0_ap_start,
        ap_done => event_queue_top_1_U0_ap_done,
        ap_continue => event_queue_top_1_U0_ap_continue,
        ap_idle => event_queue_top_1_U0_ap_idle,
        ap_ready => event_queue_top_1_U0_ap_ready,
        lpcore_init_event_stream_1_dout => lpcore_init_event_stream_1_dout,
        lpcore_init_event_stream_1_empty_n => lpcore_init_event_stream_1_empty_n,
        lpcore_init_event_stream_1_read => event_queue_top_1_U0_lpcore_init_event_stream_1_read,
        lpcore_event_queue_full_stream_1_din => event_queue_top_1_U0_lpcore_event_queue_full_stream_1_din,
        lpcore_event_queue_full_stream_1_num_data_valid => ap_const_lv2_0,
        lpcore_event_queue_full_stream_1_fifo_cap => ap_const_lv2_0,
        lpcore_event_queue_full_stream_1_full_n => lpcore_event_queue_full_stream_1_full_n,
        lpcore_event_queue_full_stream_1_write => event_queue_top_1_U0_lpcore_event_queue_full_stream_1_write,
        event_queue_rollback_info_stream_dout => event_queue_rollback_info_stream_dout,
        event_queue_rollback_info_stream_num_data_valid => event_queue_rollback_info_stream_num_data_valid,
        event_queue_rollback_info_stream_fifo_cap => event_queue_rollback_info_stream_fifo_cap,
        event_queue_rollback_info_stream_empty_n => event_queue_rollback_info_stream_empty_n,
        event_queue_rollback_info_stream_read => event_queue_top_1_U0_event_queue_rollback_info_stream_read,
        lpcore_anti_message_stream_1_dout => lpcore_anti_message_stream_1_dout,
        lpcore_anti_message_stream_1_num_data_valid => ap_const_lv2_0,
        lpcore_anti_message_stream_1_fifo_cap => ap_const_lv2_0,
        lpcore_anti_message_stream_1_empty_n => lpcore_anti_message_stream_1_empty_n,
        lpcore_anti_message_stream_1_read => event_queue_top_1_U0_lpcore_anti_message_stream_1_read,
        lpcore_enqueue_event_stream_1_dout => lpcore_enqueue_event_stream_1_dout,
        lpcore_enqueue_event_stream_1_num_data_valid => ap_const_lv2_0,
        lpcore_enqueue_event_stream_1_fifo_cap => ap_const_lv2_0,
        lpcore_enqueue_event_stream_1_empty_n => lpcore_enqueue_event_stream_1_empty_n,
        lpcore_enqueue_event_stream_1_read => event_queue_top_1_U0_lpcore_enqueue_event_stream_1_read,
        event_queue_commit_time_stream15_dout => event_queue_commit_time_stream_dout,
        event_queue_commit_time_stream15_num_data_valid => event_queue_commit_time_stream_num_data_valid,
        event_queue_commit_time_stream15_fifo_cap => event_queue_commit_time_stream_fifo_cap,
        event_queue_commit_time_stream15_empty_n => event_queue_commit_time_stream_empty_n,
        event_queue_commit_time_stream15_read => event_queue_top_1_U0_event_queue_commit_time_stream15_read,
        issued_event_stream_din => event_queue_top_1_U0_issued_event_stream_din,
        issued_event_stream_num_data_valid => issued_event_stream_num_data_valid,
        issued_event_stream_fifo_cap => issued_event_stream_fifo_cap,
        issued_event_stream_full_n => issued_event_stream_full_n,
        issued_event_stream_write => event_queue_top_1_U0_issued_event_stream_write,
        causality_violation_stream_din => event_queue_top_1_U0_causality_violation_stream_din,
        causality_violation_stream_num_data_valid => causality_violation_stream_num_data_valid,
        causality_violation_stream_fifo_cap => causality_violation_stream_fifo_cap,
        causality_violation_stream_full_n => causality_violation_stream_full_n,
        causality_violation_stream_write => event_queue_top_1_U0_causality_violation_stream_write);

    state_buffer_top_1_U0 : component simulation_top_state_buffer_top_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => state_buffer_top_1_U0_ap_start,
        ap_done => state_buffer_top_1_U0_ap_done,
        ap_continue => state_buffer_top_1_U0_ap_continue,
        ap_idle => state_buffer_top_1_U0_ap_idle,
        ap_ready => state_buffer_top_1_U0_ap_ready,
        state_buffer_rollback_info_stream_dout => state_buffer_rollback_info_stream_dout,
        state_buffer_rollback_info_stream_num_data_valid => state_buffer_rollback_info_stream_num_data_valid,
        state_buffer_rollback_info_stream_fifo_cap => state_buffer_rollback_info_stream_fifo_cap,
        state_buffer_rollback_info_stream_empty_n => state_buffer_rollback_info_stream_empty_n,
        state_buffer_rollback_info_stream_read => state_buffer_top_1_U0_state_buffer_rollback_info_stream_read,
        state_buffer_commit_time_stream16_dout => state_buffer_commit_time_stream_dout,
        state_buffer_commit_time_stream16_num_data_valid => state_buffer_commit_time_stream_num_data_valid,
        state_buffer_commit_time_stream16_fifo_cap => state_buffer_commit_time_stream_fifo_cap,
        state_buffer_commit_time_stream16_empty_n => state_buffer_commit_time_stream_empty_n,
        state_buffer_commit_time_stream16_read => state_buffer_top_1_U0_state_buffer_commit_time_stream16_read,
        state_buffer_input_stream_dout => state_buffer_input_stream_dout,
        state_buffer_input_stream_num_data_valid => state_buffer_input_stream_num_data_valid,
        state_buffer_input_stream_fifo_cap => state_buffer_input_stream_fifo_cap,
        state_buffer_input_stream_empty_n => state_buffer_input_stream_empty_n,
        state_buffer_input_stream_read => state_buffer_top_1_U0_state_buffer_input_stream_read,
        issued_event_stream_dout => issued_event_stream_dout,
        issued_event_stream_num_data_valid => issued_event_stream_num_data_valid,
        issued_event_stream_fifo_cap => issued_event_stream_fifo_cap,
        issued_event_stream_empty_n => issued_event_stream_empty_n,
        issued_event_stream_read => state_buffer_top_1_U0_issued_event_stream_read,
        event_processor_input_stream_din => state_buffer_top_1_U0_event_processor_input_stream_din,
        event_processor_input_stream_num_data_valid => event_processor_input_stream_num_data_valid,
        event_processor_input_stream_fifo_cap => event_processor_input_stream_fifo_cap,
        event_processor_input_stream_full_n => event_processor_input_stream_full_n,
        event_processor_input_stream_write => state_buffer_top_1_U0_event_processor_input_stream_write);

    event_processor_top_1_U0 : component simulation_top_event_processor_top_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => event_processor_top_1_U0_ap_start,
        ap_done => event_processor_top_1_U0_ap_done,
        ap_continue => event_processor_top_1_U0_ap_continue,
        ap_idle => event_processor_top_1_U0_ap_idle,
        ap_ready => event_processor_top_1_U0_ap_ready,
        event_processor_input_stream_dout => event_processor_input_stream_dout,
        event_processor_input_stream_num_data_valid => event_processor_input_stream_num_data_valid,
        event_processor_input_stream_fifo_cap => event_processor_input_stream_fifo_cap,
        event_processor_input_stream_empty_n => event_processor_input_stream_empty_n,
        event_processor_input_stream_read => event_processor_top_1_U0_event_processor_input_stream_read,
        state_buffer_input_stream_din => event_processor_top_1_U0_state_buffer_input_stream_din,
        state_buffer_input_stream_num_data_valid => state_buffer_input_stream_num_data_valid,
        state_buffer_input_stream_fifo_cap => state_buffer_input_stream_fifo_cap,
        state_buffer_input_stream_full_n => state_buffer_input_stream_full_n,
        state_buffer_input_stream_write => event_processor_top_1_U0_state_buffer_input_stream_write,
        lpcore_lvt_stream_1_din => event_processor_top_1_U0_lpcore_lvt_stream_1_din,
        lpcore_lvt_stream_1_num_data_valid => ap_const_lv2_0,
        lpcore_lvt_stream_1_fifo_cap => ap_const_lv2_0,
        lpcore_lvt_stream_1_full_n => lpcore_lvt_stream_1_full_n,
        lpcore_lvt_stream_1_write => event_processor_top_1_U0_lpcore_lvt_stream_1_write,
        lpcore_output_event_stream_1_din => event_processor_top_1_U0_lpcore_output_event_stream_1_din,
        lpcore_output_event_stream_1_num_data_valid => ap_const_lv2_0,
        lpcore_output_event_stream_1_fifo_cap => ap_const_lv2_0,
        lpcore_output_event_stream_1_full_n => lpcore_output_event_stream_1_full_n,
        lpcore_output_event_stream_1_write => event_processor_top_1_U0_lpcore_output_event_stream_1_write,
        cancellation_unit_input_stream_din => event_processor_top_1_U0_cancellation_unit_input_stream_din,
        cancellation_unit_input_stream_num_data_valid => cancellation_unit_input_stream_num_data_valid,
        cancellation_unit_input_stream_fifo_cap => cancellation_unit_input_stream_fifo_cap,
        cancellation_unit_input_stream_full_n => cancellation_unit_input_stream_full_n,
        cancellation_unit_input_stream_write => event_processor_top_1_U0_cancellation_unit_input_stream_write);

    cancellation_unit_top_1_U0 : component simulation_top_cancellation_unit_top_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => cancellation_unit_top_1_U0_ap_start,
        ap_done => cancellation_unit_top_1_U0_ap_done,
        ap_continue => cancellation_unit_top_1_U0_ap_continue,
        ap_idle => cancellation_unit_top_1_U0_ap_idle,
        ap_ready => cancellation_unit_top_1_U0_ap_ready,
        cancellation_unit_rollback_info_stream_dout => cancellation_unit_rollback_info_stream_dout,
        cancellation_unit_rollback_info_stream_num_data_valid => cancellation_unit_rollback_info_stream_num_data_valid,
        cancellation_unit_rollback_info_stream_fifo_cap => cancellation_unit_rollback_info_stream_fifo_cap,
        cancellation_unit_rollback_info_stream_empty_n => cancellation_unit_rollback_info_stream_empty_n,
        cancellation_unit_rollback_info_stream_read => cancellation_unit_top_1_U0_cancellation_unit_rollback_info_stream_read,
        cancellation_unit_commit_time_stream17_dout => cancellation_unit_commit_time_stream_dout,
        cancellation_unit_commit_time_stream17_num_data_valid => cancellation_unit_commit_time_stream_num_data_valid,
        cancellation_unit_commit_time_stream17_fifo_cap => cancellation_unit_commit_time_stream_fifo_cap,
        cancellation_unit_commit_time_stream17_empty_n => cancellation_unit_commit_time_stream_empty_n,
        cancellation_unit_commit_time_stream17_read => cancellation_unit_top_1_U0_cancellation_unit_commit_time_stream17_read,
        cancellation_unit_input_stream_dout => cancellation_unit_input_stream_dout,
        cancellation_unit_input_stream_num_data_valid => cancellation_unit_input_stream_num_data_valid,
        cancellation_unit_input_stream_fifo_cap => cancellation_unit_input_stream_fifo_cap,
        cancellation_unit_input_stream_empty_n => cancellation_unit_input_stream_empty_n,
        cancellation_unit_input_stream_read => cancellation_unit_top_1_U0_cancellation_unit_input_stream_read,
        lpcore_cancellation_unit_output_stream_1_din => cancellation_unit_top_1_U0_lpcore_cancellation_unit_output_stream_1_din,
        lpcore_cancellation_unit_output_stream_1_num_data_valid => ap_const_lv2_0,
        lpcore_cancellation_unit_output_stream_1_fifo_cap => ap_const_lv2_0,
        lpcore_cancellation_unit_output_stream_1_full_n => lpcore_cancellation_unit_output_stream_1_full_n,
        lpcore_cancellation_unit_output_stream_1_write => cancellation_unit_top_1_U0_lpcore_cancellation_unit_output_stream_1_write);

    causality_violation_stream_U : component simulation_top_fifo_w48_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => event_queue_top_1_U0_causality_violation_stream_din,
        if_full_n => causality_violation_stream_full_n,
        if_write => event_queue_top_1_U0_causality_violation_stream_write,
        if_dout => causality_violation_stream_dout,
        if_num_data_valid => causality_violation_stream_num_data_valid,
        if_fifo_cap => causality_violation_stream_fifo_cap,
        if_empty_n => causality_violation_stream_empty_n,
        if_read => lpcore_control_top_1_U0_causality_violation_stream_read);

    event_queue_rollback_info_stream_U : component simulation_top_fifo_w48_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lpcore_control_top_1_U0_event_queue_rollback_info_stream_din,
        if_full_n => event_queue_rollback_info_stream_full_n,
        if_write => lpcore_control_top_1_U0_event_queue_rollback_info_stream_write,
        if_dout => event_queue_rollback_info_stream_dout,
        if_num_data_valid => event_queue_rollback_info_stream_num_data_valid,
        if_fifo_cap => event_queue_rollback_info_stream_fifo_cap,
        if_empty_n => event_queue_rollback_info_stream_empty_n,
        if_read => event_queue_top_1_U0_event_queue_rollback_info_stream_read);

    state_buffer_rollback_info_stream_U : component simulation_top_fifo_w48_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lpcore_control_top_1_U0_state_buffer_rollback_info_stream_din,
        if_full_n => state_buffer_rollback_info_stream_full_n,
        if_write => lpcore_control_top_1_U0_state_buffer_rollback_info_stream_write,
        if_dout => state_buffer_rollback_info_stream_dout,
        if_num_data_valid => state_buffer_rollback_info_stream_num_data_valid,
        if_fifo_cap => state_buffer_rollback_info_stream_fifo_cap,
        if_empty_n => state_buffer_rollback_info_stream_empty_n,
        if_read => state_buffer_top_1_U0_state_buffer_rollback_info_stream_read);

    cancellation_unit_rollback_info_stream_U : component simulation_top_fifo_w48_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lpcore_control_top_1_U0_cancellation_unit_rollback_info_stream_din,
        if_full_n => cancellation_unit_rollback_info_stream_full_n,
        if_write => lpcore_control_top_1_U0_cancellation_unit_rollback_info_stream_write,
        if_dout => cancellation_unit_rollback_info_stream_dout,
        if_num_data_valid => cancellation_unit_rollback_info_stream_num_data_valid,
        if_fifo_cap => cancellation_unit_rollback_info_stream_fifo_cap,
        if_empty_n => cancellation_unit_rollback_info_stream_empty_n,
        if_read => cancellation_unit_top_1_U0_cancellation_unit_rollback_info_stream_read);

    event_queue_commit_time_stream_U : component simulation_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lpcore_control_top_1_U0_event_queue_commit_time_stream15_din,
        if_full_n => event_queue_commit_time_stream_full_n,
        if_write => lpcore_control_top_1_U0_event_queue_commit_time_stream15_write,
        if_dout => event_queue_commit_time_stream_dout,
        if_num_data_valid => event_queue_commit_time_stream_num_data_valid,
        if_fifo_cap => event_queue_commit_time_stream_fifo_cap,
        if_empty_n => event_queue_commit_time_stream_empty_n,
        if_read => event_queue_top_1_U0_event_queue_commit_time_stream15_read);

    state_buffer_commit_time_stream_U : component simulation_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lpcore_control_top_1_U0_state_buffer_commit_time_stream16_din,
        if_full_n => state_buffer_commit_time_stream_full_n,
        if_write => lpcore_control_top_1_U0_state_buffer_commit_time_stream16_write,
        if_dout => state_buffer_commit_time_stream_dout,
        if_num_data_valid => state_buffer_commit_time_stream_num_data_valid,
        if_fifo_cap => state_buffer_commit_time_stream_fifo_cap,
        if_empty_n => state_buffer_commit_time_stream_empty_n,
        if_read => state_buffer_top_1_U0_state_buffer_commit_time_stream16_read);

    cancellation_unit_commit_time_stream_U : component simulation_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lpcore_control_top_1_U0_cancellation_unit_commit_time_stream17_din,
        if_full_n => cancellation_unit_commit_time_stream_full_n,
        if_write => lpcore_control_top_1_U0_cancellation_unit_commit_time_stream17_write,
        if_dout => cancellation_unit_commit_time_stream_dout,
        if_num_data_valid => cancellation_unit_commit_time_stream_num_data_valid,
        if_fifo_cap => cancellation_unit_commit_time_stream_fifo_cap,
        if_empty_n => cancellation_unit_commit_time_stream_empty_n,
        if_read => cancellation_unit_top_1_U0_cancellation_unit_commit_time_stream17_read);

    issued_event_stream_U : component simulation_top_fifo_w129_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => event_queue_top_1_U0_issued_event_stream_din,
        if_full_n => issued_event_stream_full_n,
        if_write => event_queue_top_1_U0_issued_event_stream_write,
        if_dout => issued_event_stream_dout,
        if_num_data_valid => issued_event_stream_num_data_valid,
        if_fifo_cap => issued_event_stream_fifo_cap,
        if_empty_n => issued_event_stream_empty_n,
        if_read => state_buffer_top_1_U0_issued_event_stream_read);

    state_buffer_input_stream_U : component simulation_top_fifo_w80_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => event_processor_top_1_U0_state_buffer_input_stream_din,
        if_full_n => state_buffer_input_stream_full_n,
        if_write => event_processor_top_1_U0_state_buffer_input_stream_write,
        if_dout => state_buffer_input_stream_dout,
        if_num_data_valid => state_buffer_input_stream_num_data_valid,
        if_fifo_cap => state_buffer_input_stream_fifo_cap,
        if_empty_n => state_buffer_input_stream_empty_n,
        if_read => state_buffer_top_1_U0_state_buffer_input_stream_read);

    event_processor_input_stream_U : component simulation_top_fifo_w209_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => state_buffer_top_1_U0_event_processor_input_stream_din,
        if_full_n => event_processor_input_stream_full_n,
        if_write => state_buffer_top_1_U0_event_processor_input_stream_write,
        if_dout => event_processor_input_stream_dout,
        if_num_data_valid => event_processor_input_stream_num_data_valid,
        if_fifo_cap => event_processor_input_stream_fifo_cap,
        if_empty_n => event_processor_input_stream_empty_n,
        if_read => event_processor_top_1_U0_event_processor_input_stream_read);

    cancellation_unit_input_stream_U : component simulation_top_fifo_w129_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => event_processor_top_1_U0_cancellation_unit_input_stream_din,
        if_full_n => cancellation_unit_input_stream_full_n,
        if_write => event_processor_top_1_U0_cancellation_unit_input_stream_write,
        if_dout => cancellation_unit_input_stream_dout,
        if_num_data_valid => cancellation_unit_input_stream_num_data_valid,
        if_fifo_cap => cancellation_unit_input_stream_fifo_cap,
        if_empty_n => cancellation_unit_input_stream_empty_n,
        if_read => cancellation_unit_top_1_U0_cancellation_unit_input_stream_read);




    ap_ready <= ap_const_logic_1;
    cancellation_unit_top_1_U0_ap_continue <= ap_const_logic_1;
    cancellation_unit_top_1_U0_ap_start <= ap_const_logic_1;
    event_processor_top_1_U0_ap_continue <= ap_const_logic_1;
    event_processor_top_1_U0_ap_start <= ap_const_logic_1;
    event_queue_top_1_U0_ap_continue <= ap_const_logic_1;
    event_queue_top_1_U0_ap_start <= ap_const_logic_1;
    lpcore_anti_message_stream_1_read <= event_queue_top_1_U0_lpcore_anti_message_stream_1_read;
    lpcore_cancellation_unit_output_stream_1_din <= cancellation_unit_top_1_U0_lpcore_cancellation_unit_output_stream_1_din;
    lpcore_cancellation_unit_output_stream_1_write <= cancellation_unit_top_1_U0_lpcore_cancellation_unit_output_stream_1_write;
    lpcore_commit_time_stream_1_read <= lpcore_control_top_1_U0_lpcore_commit_time_stream_1_read;
    lpcore_enqueue_event_stream_1_read <= event_queue_top_1_U0_lpcore_enqueue_event_stream_1_read;
    lpcore_event_queue_full_stream_1_din <= event_queue_top_1_U0_lpcore_event_queue_full_stream_1_din;
    lpcore_event_queue_full_stream_1_write <= event_queue_top_1_U0_lpcore_event_queue_full_stream_1_write;
    lpcore_init_event_stream_1_read <= event_queue_top_1_U0_lpcore_init_event_stream_1_read;
    lpcore_lvt_stream_1_din <= event_processor_top_1_U0_lpcore_lvt_stream_1_din;
    lpcore_lvt_stream_1_write <= event_processor_top_1_U0_lpcore_lvt_stream_1_write;
    lpcore_output_event_stream_1_din <= event_processor_top_1_U0_lpcore_output_event_stream_1_din;
    lpcore_output_event_stream_1_write <= event_processor_top_1_U0_lpcore_output_event_stream_1_write;
    state_buffer_top_1_U0_ap_continue <= ap_const_logic_1;
    state_buffer_top_1_U0_ap_start <= ap_const_logic_1;
end behav;
