-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity simulation_top is
port (
    lpcore_init_event_stream_0_dout : IN STD_LOGIC_VECTOR (128 downto 0);
    lpcore_init_event_stream_0_empty_n : IN STD_LOGIC;
    lpcore_init_event_stream_0_read : OUT STD_LOGIC;
    lpcore_init_event_stream_1_dout : IN STD_LOGIC_VECTOR (128 downto 0);
    lpcore_init_event_stream_1_empty_n : IN STD_LOGIC;
    lpcore_init_event_stream_1_read : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC );
end;


architecture behav of simulation_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "simulation_top_simulation_top,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.937000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=34,HLS_SYN_DSP=0,HLS_SYN_FF=11443,HLS_SYN_LUT=17259,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal KPN_1_U0_lpcore_init_event_stream_0_read : STD_LOGIC;
    signal KPN_1_U0_lpcore_init_event_stream_1_read : STD_LOGIC;
    signal KPN_1_U0_ap_ready : STD_LOGIC;

    component simulation_top_KPN_1 IS
    port (
        lpcore_init_event_stream_0_dout : IN STD_LOGIC_VECTOR (128 downto 0);
        lpcore_init_event_stream_0_empty_n : IN STD_LOGIC;
        lpcore_init_event_stream_0_read : OUT STD_LOGIC;
        lpcore_init_event_stream_1_dout : IN STD_LOGIC_VECTOR (128 downto 0);
        lpcore_init_event_stream_1_empty_n : IN STD_LOGIC;
        lpcore_init_event_stream_1_read : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC );
    end component;



begin
    KPN_1_U0 : component simulation_top_KPN_1
    port map (
        lpcore_init_event_stream_0_dout => lpcore_init_event_stream_0_dout,
        lpcore_init_event_stream_0_empty_n => lpcore_init_event_stream_0_empty_n,
        lpcore_init_event_stream_0_read => KPN_1_U0_lpcore_init_event_stream_0_read,
        lpcore_init_event_stream_1_dout => lpcore_init_event_stream_1_dout,
        lpcore_init_event_stream_1_empty_n => lpcore_init_event_stream_1_empty_n,
        lpcore_init_event_stream_1_read => KPN_1_U0_lpcore_init_event_stream_1_read,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_ready => KPN_1_U0_ap_ready);




    lpcore_init_event_stream_0_read <= KPN_1_U0_lpcore_init_event_stream_0_read;
    lpcore_init_event_stream_1_read <= KPN_1_U0_lpcore_init_event_stream_1_read;
end behav;
