-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity state_buffer_kernel_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    current_V : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln587_5 : IN STD_LOGIC_VECTOR (5 downto 0);
    commit_time_V : IN STD_LOGIC_VECTOR (31 downto 0);
    removed_V_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    removed_V_out_ap_vld : OUT STD_LOGIC;
    list_nodes_next_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    list_nodes_next_V_ce0 : OUT STD_LOGIC;
    list_nodes_next_V_we0 : OUT STD_LOGIC;
    list_nodes_next_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    list_nodes_next_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    list_lp_heads_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    list_lp_heads_V_ce0 : OUT STD_LOGIC;
    list_lp_heads_V_we0 : OUT STD_LOGIC;
    list_lp_heads_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    list_free_head_V_i : IN STD_LOGIC_VECTOR (15 downto 0);
    list_free_head_V_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    list_free_head_V_o_ap_vld : OUT STD_LOGIC;
    list_nodes_state_lvt_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    list_nodes_state_lvt_V_ce0 : OUT STD_LOGIC;
    list_nodes_state_lvt_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of state_buffer_kernel_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln1081_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_reg_271 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal current_V_2_reg_261 : STD_LOGIC_VECTOR (15 downto 0);
    signal list_lp_heads_V_addr_reg_266 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln1069_fu_155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln587_fu_161_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_reg_275 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal reuse_reg_load_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal addr_cmp_fu_187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_reg_300 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln587_5_cast_fu_127_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal reuse_addr_reg_fu_48 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal reuse_reg_fu_52 : STD_LOGIC_VECTOR (15 downto 0);
    signal current_V_1_fu_56 : STD_LOGIC_VECTOR (15 downto 0);
    signal current_V_3_fu_216_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_current_V_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal removed_V_fu_60 : STD_LOGIC_VECTOR (15 downto 0);
    signal removed_V_2_fu_170_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component state_buffer_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component state_buffer_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    current_V_1_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    current_V_1_fu_56 <= current_V;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    current_V_1_fu_56 <= current_V_3_fu_216_p3;
                end if;
            end if; 
        end if;
    end process;

    removed_V_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                removed_V_fu_60 <= ap_const_lv16_0;
            elsif (((icmp_ln1069_reg_271 = ap_const_lv1_0) and (icmp_ln1081_fu_176_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                removed_V_fu_60 <= removed_V_2_fu_170_p2;
            end if; 
        end if;
    end process;

    reuse_addr_reg_fu_48_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                reuse_addr_reg_fu_48 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
            elsif (((icmp_ln1069_reg_271 = ap_const_lv1_0) and (icmp_ln1081_fu_176_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                reuse_addr_reg_fu_48 <= zext_ln587_reg_275;
            end if; 
        end if;
    end process;

    reuse_reg_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                reuse_reg_fu_52 <= ap_const_lv16_0;
            elsif (((icmp_ln1069_reg_271 = ap_const_lv1_0) and (icmp_ln1081_fu_176_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                reuse_reg_fu_52 <= list_free_head_V_i;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1069_reg_271 = ap_const_lv1_0) and (icmp_ln1081_fu_176_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                addr_cmp_reg_300 <= addr_cmp_fu_187_p2;
                reuse_reg_load_reg_295 <= reuse_reg_fu_52;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                current_V_2_reg_261 <= ap_sig_allocacmp_current_V_2;
                icmp_ln1069_reg_271 <= icmp_ln1069_fu_155_p2;
                list_lp_heads_V_addr_reg_266 <= zext_ln587_5_cast_fu_127_p1(6 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1069_fu_155_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    zext_ln587_reg_275(15 downto 0) <= zext_ln587_fu_161_p1(15 downto 0);
            end if;
        end if;
    end process;
    zext_ln587_reg_275(63 downto 16) <= "000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    addr_cmp_fu_187_p2 <= "1" when (reuse_addr_reg_fu_48 = zext_ln587_reg_275) else "0";
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln1081_fu_176_p2, icmp_ln1069_reg_271)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and ((icmp_ln1069_reg_271 = ap_const_lv1_1) or (icmp_ln1081_fu_176_p2 = ap_const_lv1_0)))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_current_V_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, current_V, ap_block_pp0_stage0, ap_loop_init, current_V_1_fu_56, current_V_3_fu_216_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_current_V_2 <= current_V;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_current_V_2 <= current_V_3_fu_216_p3;
            else 
                ap_sig_allocacmp_current_V_2 <= current_V_1_fu_56;
            end if;
        else 
            ap_sig_allocacmp_current_V_2 <= current_V_1_fu_56;
        end if; 
    end process;

    current_V_3_fu_216_p3 <= 
        reuse_reg_load_reg_295 when (addr_cmp_reg_300(0) = '1') else 
        list_nodes_next_V_q0;
    icmp_ln1069_fu_155_p2 <= "1" when (ap_sig_allocacmp_current_V_2 = ap_const_lv16_FFFF) else "0";
    icmp_ln1081_fu_176_p2 <= "1" when (signed(list_nodes_state_lvt_V_q0) > signed(commit_time_V)) else "0";

    list_free_head_V_o_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln1081_fu_176_p2, icmp_ln1069_reg_271, list_free_head_V_i, current_V_2_reg_261, ap_block_pp0_stage1)
    begin
        if (((icmp_ln1069_reg_271 = ap_const_lv1_0) and (icmp_ln1081_fu_176_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            list_free_head_V_o <= current_V_2_reg_261;
        else 
            list_free_head_V_o <= list_free_head_V_i;
        end if; 
    end process;


    list_free_head_V_o_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln1081_fu_176_p2, icmp_ln1069_reg_271, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln1069_reg_271 = ap_const_lv1_0) and (icmp_ln1081_fu_176_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            list_free_head_V_o_ap_vld <= ap_const_logic_1;
        else 
            list_free_head_V_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    list_lp_heads_V_address0 <= list_lp_heads_V_addr_reg_266;

    list_lp_heads_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            list_lp_heads_V_ce0 <= ap_const_logic_1;
        else 
            list_lp_heads_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    list_lp_heads_V_d0 <= 
        reuse_reg_load_reg_295 when (addr_cmp_reg_300(0) = '1') else 
        list_nodes_next_V_q0;

    list_lp_heads_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            list_lp_heads_V_we0 <= ap_const_logic_1;
        else 
            list_lp_heads_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    list_nodes_next_V_address0 <= zext_ln587_reg_275(7 - 1 downto 0);

    list_nodes_next_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln1081_fu_176_p2, icmp_ln1069_reg_271, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln1069_reg_271 = ap_const_lv1_0) and (icmp_ln1081_fu_176_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            list_nodes_next_V_ce0 <= ap_const_logic_1;
        else 
            list_nodes_next_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    list_nodes_next_V_d0 <= list_free_head_V_i;

    list_nodes_next_V_we0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln1081_fu_176_p2, icmp_ln1069_reg_271, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln1069_reg_271 = ap_const_lv1_0) and (icmp_ln1081_fu_176_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            list_nodes_next_V_we0 <= ap_const_logic_1;
        else 
            list_nodes_next_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    list_nodes_state_lvt_V_address0 <= zext_ln587_fu_161_p1(7 - 1 downto 0);

    list_nodes_state_lvt_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            list_nodes_state_lvt_V_ce0 <= ap_const_logic_1;
        else 
            list_nodes_state_lvt_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    removed_V_2_fu_170_p2 <= std_logic_vector(unsigned(removed_V_fu_60) + unsigned(ap_const_lv16_1));
    removed_V_out <= removed_V_fu_60;

    removed_V_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln1081_fu_176_p2, icmp_ln1069_reg_271, ap_block_pp0_stage1_11001)
    begin
        if ((((icmp_ln1069_reg_271 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((icmp_ln1069_reg_271 = ap_const_lv1_0) and (icmp_ln1081_fu_176_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            removed_V_out_ap_vld <= ap_const_logic_1;
        else 
            removed_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln587_5_cast_fu_127_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln587_5),64));
    zext_ln587_fu_161_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_current_V_2),64));
end behav;
