-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity simulation_top_event_router_top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    lpcore_output_event_stream_0_dout : IN STD_LOGIC_VECTOR (128 downto 0);
    lpcore_output_event_stream_0_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_output_event_stream_0_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_output_event_stream_0_empty_n : IN STD_LOGIC;
    lpcore_output_event_stream_0_read : OUT STD_LOGIC;
    lpcore_output_event_stream_1_dout : IN STD_LOGIC_VECTOR (128 downto 0);
    lpcore_output_event_stream_1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_output_event_stream_1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_output_event_stream_1_empty_n : IN STD_LOGIC;
    lpcore_output_event_stream_1_read : OUT STD_LOGIC;
    lpcore_cancellation_unit_output_stream_0_dout : IN STD_LOGIC_VECTOR (128 downto 0);
    lpcore_cancellation_unit_output_stream_0_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_cancellation_unit_output_stream_0_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_cancellation_unit_output_stream_0_empty_n : IN STD_LOGIC;
    lpcore_cancellation_unit_output_stream_0_read : OUT STD_LOGIC;
    lpcore_cancellation_unit_output_stream_1_dout : IN STD_LOGIC_VECTOR (128 downto 0);
    lpcore_cancellation_unit_output_stream_1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_cancellation_unit_output_stream_1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_cancellation_unit_output_stream_1_empty_n : IN STD_LOGIC;
    lpcore_cancellation_unit_output_stream_1_read : OUT STD_LOGIC;
    lpcore_enqueue_event_stream_0_din : OUT STD_LOGIC_VECTOR (128 downto 0);
    lpcore_enqueue_event_stream_0_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_enqueue_event_stream_0_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_enqueue_event_stream_0_full_n : IN STD_LOGIC;
    lpcore_enqueue_event_stream_0_write : OUT STD_LOGIC;
    lpcore_enqueue_event_stream_1_din : OUT STD_LOGIC_VECTOR (128 downto 0);
    lpcore_enqueue_event_stream_1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_enqueue_event_stream_1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_enqueue_event_stream_1_full_n : IN STD_LOGIC;
    lpcore_enqueue_event_stream_1_write : OUT STD_LOGIC;
    lpcore_anti_message_stream_0_din : OUT STD_LOGIC_VECTOR (128 downto 0);
    lpcore_anti_message_stream_0_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_anti_message_stream_0_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_anti_message_stream_0_full_n : IN STD_LOGIC;
    lpcore_anti_message_stream_0_write : OUT STD_LOGIC;
    lpcore_anti_message_stream_1_din : OUT STD_LOGIC_VECTOR (128 downto 0);
    lpcore_anti_message_stream_1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_anti_message_stream_1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    lpcore_anti_message_stream_1_full_n : IN STD_LOGIC;
    lpcore_anti_message_stream_1_write : OUT STD_LOGIC );
end;


architecture behav of simulation_top_event_router_top is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal lpcore_output_event_stream_0_blk_n : STD_LOGIC;
    signal tmp_nbreadreq_fu_38_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal lpcore_output_event_stream_1_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_2_reg_174 : STD_LOGIC_VECTOR (0 downto 0);
    signal lpcore_cancellation_unit_output_stream_0_blk_n : STD_LOGIC;
    signal tmp_s_nbreadreq_fu_68_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal lpcore_cancellation_unit_output_stream_1_blk_n : STD_LOGIC;
    signal tmp_3_nbreadreq_fu_114_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal lpcore_enqueue_event_stream_0_blk_n : STD_LOGIC;
    signal tmp_19_fu_130_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_146_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal lpcore_enqueue_event_stream_1_blk_n : STD_LOGIC;
    signal lpcore_anti_message_stream_0_blk_n : STD_LOGIC;
    signal tmp_20_fu_138_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_154_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal lpcore_anti_message_stream_1_blk_n : STD_LOGIC;
    signal tmp_2_nbreadreq_fu_98_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op16_write_state1 : BOOLEAN;
    signal ap_predicate_op18_write_state1 : BOOLEAN;
    signal ap_predicate_op26_write_state1 : BOOLEAN;
    signal ap_predicate_op28_write_state1 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal ap_predicate_op36_write_state2 : BOOLEAN;
    signal ap_predicate_op38_write_state2 : BOOLEAN;
    signal ap_predicate_op46_write_state2 : BOOLEAN;
    signal ap_predicate_op48_write_state2 : BOOLEAN;
    signal ap_block_state2 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                tmp_2_reg_174 <= tmp_2_nbreadreq_fu_98_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, lpcore_output_event_stream_0_empty_n, lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_0_empty_n, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_nbreadreq_fu_38_p3, ap_CS_fsm_state2, tmp_2_reg_174, tmp_s_nbreadreq_fu_68_p3, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op16_write_state1, ap_predicate_op18_write_state1, ap_predicate_op26_write_state1, ap_predicate_op28_write_state1, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_0_empty_n = ap_const_logic_0)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (lpcore_output_event_stream_0_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, lpcore_output_event_stream_0_empty_n, lpcore_cancellation_unit_output_stream_0_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_nbreadreq_fu_38_p3, tmp_s_nbreadreq_fu_68_p3, ap_predicate_op16_write_state1, ap_predicate_op18_write_state1, ap_predicate_op26_write_state1, ap_predicate_op28_write_state1)
    begin
        if (((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_0_empty_n = ap_const_logic_0)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (lpcore_output_event_stream_0_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_2_reg_174, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        if ((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, lpcore_output_event_stream_0_empty_n, lpcore_cancellation_unit_output_stream_0_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_nbreadreq_fu_38_p3, tmp_s_nbreadreq_fu_68_p3, ap_predicate_op16_write_state1, ap_predicate_op18_write_state1, ap_predicate_op26_write_state1, ap_predicate_op28_write_state1)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_0_empty_n = ap_const_logic_0)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (lpcore_output_event_stream_0_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)));
    end process;


    ap_block_state2_assign_proc : process(lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_2_reg_174, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
                ap_block_state2 <= (((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, ap_CS_fsm_state2, tmp_2_reg_174, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        if ((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op16_write_state1_assign_proc : process(tmp_nbreadreq_fu_38_p3, tmp_19_fu_130_p3)
    begin
                ap_predicate_op16_write_state1 <= ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (tmp_19_fu_130_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op18_write_state1_assign_proc : process(tmp_nbreadreq_fu_38_p3, tmp_19_fu_130_p3)
    begin
                ap_predicate_op18_write_state1 <= ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (tmp_19_fu_130_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op26_write_state1_assign_proc : process(tmp_s_nbreadreq_fu_68_p3, tmp_20_fu_138_p3)
    begin
                ap_predicate_op26_write_state1 <= ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (tmp_20_fu_138_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op28_write_state1_assign_proc : process(tmp_s_nbreadreq_fu_68_p3, tmp_20_fu_138_p3)
    begin
                ap_predicate_op28_write_state1 <= ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (tmp_20_fu_138_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op36_write_state2_assign_proc : process(tmp_2_reg_174, tmp_21_fu_146_p3)
    begin
                ap_predicate_op36_write_state2 <= ((tmp_2_reg_174 = ap_const_lv1_1) and (tmp_21_fu_146_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op38_write_state2_assign_proc : process(tmp_2_reg_174, tmp_21_fu_146_p3)
    begin
                ap_predicate_op38_write_state2 <= ((tmp_2_reg_174 = ap_const_lv1_1) and (tmp_21_fu_146_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op46_write_state2_assign_proc : process(tmp_3_nbreadreq_fu_114_p3, tmp_22_fu_154_p3)
    begin
                ap_predicate_op46_write_state2 <= ((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (tmp_22_fu_154_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op48_write_state2_assign_proc : process(tmp_3_nbreadreq_fu_114_p3, tmp_22_fu_154_p3)
    begin
                ap_predicate_op48_write_state2 <= ((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (tmp_22_fu_154_p3 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, ap_CS_fsm_state2, tmp_2_reg_174, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        if ((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    lpcore_anti_message_stream_0_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_anti_message_stream_0_full_n, ap_CS_fsm_state2, tmp_s_nbreadreq_fu_68_p3, tmp_3_nbreadreq_fu_114_p3, tmp_20_fu_138_p3, tmp_22_fu_154_p3)
    begin
        if ((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_22_fu_154_p3 = ap_const_lv1_0)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_20_fu_138_p3 = ap_const_lv1_0)))) then 
            lpcore_anti_message_stream_0_blk_n <= lpcore_anti_message_stream_0_full_n;
        else 
            lpcore_anti_message_stream_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lpcore_anti_message_stream_0_din_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_output_event_stream_0_empty_n, lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_0_dout, lpcore_cancellation_unit_output_stream_0_empty_n, lpcore_cancellation_unit_output_stream_1_dout, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_nbreadreq_fu_38_p3, ap_CS_fsm_state2, tmp_2_reg_174, tmp_s_nbreadreq_fu_68_p3, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op16_write_state1, ap_predicate_op18_write_state1, ap_predicate_op26_write_state1, ap_predicate_op28_write_state1, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        if ((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op46_write_state2 = ap_const_boolean_1))) then 
            lpcore_anti_message_stream_0_din <= lpcore_cancellation_unit_output_stream_1_dout;
        elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_0_empty_n = ap_const_logic_0)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (lpcore_output_event_stream_0_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op26_write_state1 = ap_const_boolean_1))) then 
            lpcore_anti_message_stream_0_din <= lpcore_cancellation_unit_output_stream_0_dout;
        else 
            lpcore_anti_message_stream_0_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    lpcore_anti_message_stream_0_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_output_event_stream_0_empty_n, lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_0_empty_n, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_nbreadreq_fu_38_p3, ap_CS_fsm_state2, tmp_2_reg_174, tmp_s_nbreadreq_fu_68_p3, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op16_write_state1, ap_predicate_op18_write_state1, ap_predicate_op26_write_state1, ap_predicate_op28_write_state1, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        if (((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_0_empty_n = ap_const_logic_0)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (lpcore_output_event_stream_0_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)))) then 
            lpcore_anti_message_stream_0_write <= ap_const_logic_1;
        else 
            lpcore_anti_message_stream_0_write <= ap_const_logic_0;
        end if; 
    end process;


    lpcore_anti_message_stream_1_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_anti_message_stream_1_full_n, ap_CS_fsm_state2, tmp_s_nbreadreq_fu_68_p3, tmp_3_nbreadreq_fu_114_p3, tmp_20_fu_138_p3, tmp_22_fu_154_p3)
    begin
        if ((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_22_fu_154_p3 = ap_const_lv1_1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_20_fu_138_p3 = ap_const_lv1_1)))) then 
            lpcore_anti_message_stream_1_blk_n <= lpcore_anti_message_stream_1_full_n;
        else 
            lpcore_anti_message_stream_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lpcore_anti_message_stream_1_din_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_output_event_stream_0_empty_n, lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_0_dout, lpcore_cancellation_unit_output_stream_0_empty_n, lpcore_cancellation_unit_output_stream_1_dout, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_nbreadreq_fu_38_p3, ap_CS_fsm_state2, tmp_2_reg_174, tmp_s_nbreadreq_fu_68_p3, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op16_write_state1, ap_predicate_op18_write_state1, ap_predicate_op26_write_state1, ap_predicate_op28_write_state1, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        if ((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op48_write_state2 = ap_const_boolean_1))) then 
            lpcore_anti_message_stream_1_din <= lpcore_cancellation_unit_output_stream_1_dout;
        elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_0_empty_n = ap_const_logic_0)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (lpcore_output_event_stream_0_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op28_write_state1 = ap_const_boolean_1))) then 
            lpcore_anti_message_stream_1_din <= lpcore_cancellation_unit_output_stream_0_dout;
        else 
            lpcore_anti_message_stream_1_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    lpcore_anti_message_stream_1_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_output_event_stream_0_empty_n, lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_0_empty_n, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_nbreadreq_fu_38_p3, ap_CS_fsm_state2, tmp_2_reg_174, tmp_s_nbreadreq_fu_68_p3, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op16_write_state1, ap_predicate_op18_write_state1, ap_predicate_op26_write_state1, ap_predicate_op28_write_state1, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        if (((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_0_empty_n = ap_const_logic_0)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (lpcore_output_event_stream_0_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)))) then 
            lpcore_anti_message_stream_1_write <= ap_const_logic_1;
        else 
            lpcore_anti_message_stream_1_write <= ap_const_logic_0;
        end if; 
    end process;


    lpcore_cancellation_unit_output_stream_0_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_cancellation_unit_output_stream_0_empty_n, tmp_s_nbreadreq_fu_68_p3)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            lpcore_cancellation_unit_output_stream_0_blk_n <= lpcore_cancellation_unit_output_stream_0_empty_n;
        else 
            lpcore_cancellation_unit_output_stream_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lpcore_cancellation_unit_output_stream_0_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_output_event_stream_0_empty_n, lpcore_cancellation_unit_output_stream_0_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_nbreadreq_fu_38_p3, tmp_s_nbreadreq_fu_68_p3, ap_predicate_op16_write_state1, ap_predicate_op18_write_state1, ap_predicate_op26_write_state1, ap_predicate_op28_write_state1)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_0_empty_n = ap_const_logic_0)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (lpcore_output_event_stream_0_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)))) and (tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            lpcore_cancellation_unit_output_stream_0_read <= ap_const_logic_1;
        else 
            lpcore_cancellation_unit_output_stream_0_read <= ap_const_logic_0;
        end if; 
    end process;


    lpcore_cancellation_unit_output_stream_1_blk_n_assign_proc : process(lpcore_cancellation_unit_output_stream_1_empty_n, ap_CS_fsm_state2, tmp_3_nbreadreq_fu_114_p3)
    begin
        if (((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            lpcore_cancellation_unit_output_stream_1_blk_n <= lpcore_cancellation_unit_output_stream_1_empty_n;
        else 
            lpcore_cancellation_unit_output_stream_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lpcore_cancellation_unit_output_stream_1_read_assign_proc : process(lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, ap_CS_fsm_state2, tmp_2_reg_174, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        if ((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            lpcore_cancellation_unit_output_stream_1_read <= ap_const_logic_1;
        else 
            lpcore_cancellation_unit_output_stream_1_read <= ap_const_logic_0;
        end if; 
    end process;


    lpcore_enqueue_event_stream_0_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_enqueue_event_stream_0_full_n, tmp_nbreadreq_fu_38_p3, ap_CS_fsm_state2, tmp_2_reg_174, tmp_19_fu_130_p3, tmp_21_fu_146_p3)
    begin
        if ((((tmp_2_reg_174 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_21_fu_146_p3 = ap_const_lv1_0)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_19_fu_130_p3 = ap_const_lv1_0)))) then 
            lpcore_enqueue_event_stream_0_blk_n <= lpcore_enqueue_event_stream_0_full_n;
        else 
            lpcore_enqueue_event_stream_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lpcore_enqueue_event_stream_0_din_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_output_event_stream_0_dout, lpcore_output_event_stream_0_empty_n, lpcore_output_event_stream_1_dout, lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_0_empty_n, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_nbreadreq_fu_38_p3, ap_CS_fsm_state2, tmp_2_reg_174, tmp_s_nbreadreq_fu_68_p3, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op16_write_state1, ap_predicate_op18_write_state1, ap_predicate_op26_write_state1, ap_predicate_op28_write_state1, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        if ((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op36_write_state2 = ap_const_boolean_1))) then 
            lpcore_enqueue_event_stream_0_din <= lpcore_output_event_stream_1_dout;
        elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_0_empty_n = ap_const_logic_0)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (lpcore_output_event_stream_0_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op16_write_state1 = ap_const_boolean_1))) then 
            lpcore_enqueue_event_stream_0_din <= lpcore_output_event_stream_0_dout;
        else 
            lpcore_enqueue_event_stream_0_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    lpcore_enqueue_event_stream_0_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_output_event_stream_0_empty_n, lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_0_empty_n, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_nbreadreq_fu_38_p3, ap_CS_fsm_state2, tmp_2_reg_174, tmp_s_nbreadreq_fu_68_p3, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op16_write_state1, ap_predicate_op18_write_state1, ap_predicate_op26_write_state1, ap_predicate_op28_write_state1, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        if (((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_0_empty_n = ap_const_logic_0)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (lpcore_output_event_stream_0_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)))) then 
            lpcore_enqueue_event_stream_0_write <= ap_const_logic_1;
        else 
            lpcore_enqueue_event_stream_0_write <= ap_const_logic_0;
        end if; 
    end process;


    lpcore_enqueue_event_stream_1_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_enqueue_event_stream_1_full_n, tmp_nbreadreq_fu_38_p3, ap_CS_fsm_state2, tmp_2_reg_174, tmp_19_fu_130_p3, tmp_21_fu_146_p3)
    begin
        if ((((tmp_2_reg_174 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_21_fu_146_p3 = ap_const_lv1_1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_19_fu_130_p3 = ap_const_lv1_1)))) then 
            lpcore_enqueue_event_stream_1_blk_n <= lpcore_enqueue_event_stream_1_full_n;
        else 
            lpcore_enqueue_event_stream_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lpcore_enqueue_event_stream_1_din_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_output_event_stream_0_dout, lpcore_output_event_stream_0_empty_n, lpcore_output_event_stream_1_dout, lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_0_empty_n, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_nbreadreq_fu_38_p3, ap_CS_fsm_state2, tmp_2_reg_174, tmp_s_nbreadreq_fu_68_p3, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op16_write_state1, ap_predicate_op18_write_state1, ap_predicate_op26_write_state1, ap_predicate_op28_write_state1, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        if ((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op38_write_state2 = ap_const_boolean_1))) then 
            lpcore_enqueue_event_stream_1_din <= lpcore_output_event_stream_1_dout;
        elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_0_empty_n = ap_const_logic_0)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (lpcore_output_event_stream_0_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op18_write_state1 = ap_const_boolean_1))) then 
            lpcore_enqueue_event_stream_1_din <= lpcore_output_event_stream_0_dout;
        else 
            lpcore_enqueue_event_stream_1_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    lpcore_enqueue_event_stream_1_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_output_event_stream_0_empty_n, lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_0_empty_n, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_nbreadreq_fu_38_p3, ap_CS_fsm_state2, tmp_2_reg_174, tmp_s_nbreadreq_fu_68_p3, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op16_write_state1, ap_predicate_op18_write_state1, ap_predicate_op26_write_state1, ap_predicate_op28_write_state1, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        if (((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_0_empty_n = ap_const_logic_0)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (lpcore_output_event_stream_0_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)))) then 
            lpcore_enqueue_event_stream_1_write <= ap_const_logic_1;
        else 
            lpcore_enqueue_event_stream_1_write <= ap_const_logic_0;
        end if; 
    end process;


    lpcore_output_event_stream_0_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_output_event_stream_0_empty_n, tmp_nbreadreq_fu_38_p3)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            lpcore_output_event_stream_0_blk_n <= lpcore_output_event_stream_0_empty_n;
        else 
            lpcore_output_event_stream_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lpcore_output_event_stream_0_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, lpcore_output_event_stream_0_empty_n, lpcore_cancellation_unit_output_stream_0_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, tmp_nbreadreq_fu_38_p3, tmp_s_nbreadreq_fu_68_p3, ap_predicate_op16_write_state1, ap_predicate_op18_write_state1, ap_predicate_op26_write_state1, ap_predicate_op28_write_state1)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_s_nbreadreq_fu_68_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_0_empty_n = ap_const_logic_0)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (lpcore_output_event_stream_0_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op28_write_state1 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op26_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op18_write_state1 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op16_write_state1 = ap_const_boolean_1)))) and (tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            lpcore_output_event_stream_0_read <= ap_const_logic_1;
        else 
            lpcore_output_event_stream_0_read <= ap_const_logic_0;
        end if; 
    end process;


    lpcore_output_event_stream_1_blk_n_assign_proc : process(lpcore_output_event_stream_1_empty_n, ap_CS_fsm_state2, tmp_2_reg_174)
    begin
        if (((tmp_2_reg_174 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            lpcore_output_event_stream_1_blk_n <= lpcore_output_event_stream_1_empty_n;
        else 
            lpcore_output_event_stream_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lpcore_output_event_stream_1_read_assign_proc : process(lpcore_output_event_stream_1_empty_n, lpcore_cancellation_unit_output_stream_1_empty_n, lpcore_enqueue_event_stream_0_full_n, lpcore_enqueue_event_stream_1_full_n, lpcore_anti_message_stream_0_full_n, lpcore_anti_message_stream_1_full_n, ap_CS_fsm_state2, tmp_2_reg_174, tmp_3_nbreadreq_fu_114_p3, ap_predicate_op36_write_state2, ap_predicate_op38_write_state2, ap_predicate_op46_write_state2, ap_predicate_op48_write_state2)
    begin
        if ((not((((tmp_3_nbreadreq_fu_114_p3 = ap_const_lv1_1) and (lpcore_cancellation_unit_output_stream_1_empty_n = ap_const_logic_0)) or ((tmp_2_reg_174 = ap_const_lv1_1) and (lpcore_output_event_stream_1_empty_n = ap_const_logic_0)) or ((lpcore_anti_message_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op48_write_state2 = ap_const_boolean_1)) or ((lpcore_anti_message_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op46_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_1_full_n = ap_const_logic_0) and (ap_predicate_op38_write_state2 = ap_const_boolean_1)) or ((lpcore_enqueue_event_stream_0_full_n = ap_const_logic_0) and (ap_predicate_op36_write_state2 = ap_const_boolean_1)))) and (tmp_2_reg_174 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            lpcore_output_event_stream_1_read <= ap_const_logic_1;
        else 
            lpcore_output_event_stream_1_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_19_fu_130_p3 <= lpcore_output_event_stream_0_dout(112 downto 112);
    tmp_20_fu_138_p3 <= lpcore_cancellation_unit_output_stream_0_dout(112 downto 112);
    tmp_21_fu_146_p3 <= lpcore_output_event_stream_1_dout(112 downto 112);
    tmp_22_fu_154_p3 <= lpcore_cancellation_unit_output_stream_1_dout(112 downto 112);
    tmp_2_nbreadreq_fu_98_p3 <= (0=>(lpcore_output_event_stream_1_empty_n), others=>'-');
    tmp_3_nbreadreq_fu_114_p3 <= (0=>(lpcore_cancellation_unit_output_stream_1_empty_n), others=>'-');
    tmp_nbreadreq_fu_38_p3 <= (0=>(lpcore_output_event_stream_0_empty_n), others=>'-');
    tmp_s_nbreadreq_fu_68_p3 <= (0=>(lpcore_cancellation_unit_output_stream_0_empty_n), others=>'-');
end behav;
