#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("lpcore_init_event_stream_0_dout", 129, hls_in, 0, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_init_event_stream_0_empty_n", 1, hls_in, 0, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_init_event_stream_0_read", 1, hls_out, 0, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_init_event_stream_1_dout", 129, hls_in, 1, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_init_event_stream_1_empty_n", 1, hls_in, 1, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_init_event_stream_1_read", 1, hls_out, 1, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_event_queue_full_stream_0_din", 1, hls_out, 2, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_event_queue_full_stream_0_full_n", 1, hls_in, 2, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_event_queue_full_stream_0_write", 1, hls_out, 2, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_event_queue_full_stream_1_din", 1, hls_out, 3, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_event_queue_full_stream_1_full_n", 1, hls_in, 3, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_event_queue_full_stream_1_write", 1, hls_out, 3, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_anti_message_stream_0_dout", 129, hls_in, 4, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_anti_message_stream_0_empty_n", 1, hls_in, 4, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_anti_message_stream_0_read", 1, hls_out, 4, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_anti_message_stream_1_dout", 129, hls_in, 5, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_anti_message_stream_1_empty_n", 1, hls_in, 5, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_anti_message_stream_1_read", 1, hls_out, 5, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_enqueue_event_stream_0_dout", 129, hls_in, 6, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_enqueue_event_stream_0_empty_n", 1, hls_in, 6, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_enqueue_event_stream_0_read", 1, hls_out, 6, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_enqueue_event_stream_1_dout", 129, hls_in, 7, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_enqueue_event_stream_1_empty_n", 1, hls_in, 7, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_enqueue_event_stream_1_read", 1, hls_out, 7, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_output_event_stream_0_din", 129, hls_out, 8, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_output_event_stream_0_full_n", 1, hls_in, 8, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_output_event_stream_0_write", 1, hls_out, 8, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_output_event_stream_1_din", 129, hls_out, 9, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_output_event_stream_1_full_n", 1, hls_in, 9, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_output_event_stream_1_write", 1, hls_out, 9, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_cancellation_unit_output_stream_0_din", 129, hls_out, 10, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_cancellation_unit_output_stream_0_full_n", 1, hls_in, 10, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_cancellation_unit_output_stream_0_write", 1, hls_out, 10, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_cancellation_unit_output_stream_1_din", 129, hls_out, 11, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_cancellation_unit_output_stream_1_full_n", 1, hls_in, 11, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_cancellation_unit_output_stream_1_write", 1, hls_out, 11, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_commit_time_stream_0_dout", 32, hls_in, 12, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_commit_time_stream_0_empty_n", 1, hls_in, 12, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_commit_time_stream_0_read", 1, hls_out, 12, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_commit_time_stream_1_dout", 32, hls_in, 13, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_commit_time_stream_1_empty_n", 1, hls_in, 13, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_commit_time_stream_1_read", 1, hls_out, 13, "ap_fifo", "fifo_data", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "simulation_top";
