#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_continue", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("op", 3, hls_in, 0, "ap_vld", "in_data", 1),
	Port_Property("op_ap_vld", 1, hls_in, 0, "ap_vld", "in_vld", 1),
	Port_Property("event_r", 160, hls_in, 1, "ap_vld", "in_data", 1),
	Port_Property("event_r_ap_vld", 1, hls_in, 1, "ap_vld", "in_vld", 1),
	Port_Property("lp_id", 16, hls_in, 2, "ap_vld", "in_data", 1),
	Port_Property("lp_id_ap_vld", 1, hls_in, 2, "ap_vld", "in_vld", 1),
	Port_Property("time_r", 32, hls_in, 3, "ap_vld", "in_data", 1),
	Port_Property("time_r_ap_vld", 1, hls_in, 3, "ap_vld", "in_vld", 1),
	Port_Property("result_entry_i", 146, hls_in, 4, "ap_vld", "in_data", 1),
	Port_Property("result_entry_o", 146, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("result_entry_i_ap_vld", 1, hls_in, 4, "ap_vld", "in_vld", 1),
	Port_Property("result_entry_o_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("success", 1, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("success_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "event_queue_kernel";
