#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("init_event_stream_dout", 129, hls_in, 0, "ap_fifo", "fifo_port_we", 1),
	Port_Property("init_event_stream_empty_n", 1, hls_in, 0, "ap_fifo", "fifo_status", 1),
	Port_Property("init_event_stream_read", 1, hls_out, 0, "ap_fifo", "fifo_data", 1),
	Port_Property("event_queue_full_stream_din", 1, hls_out, 1, "ap_fifo", "fifo_port_we", 1),
	Port_Property("event_queue_full_stream_full_n", 1, hls_in, 1, "ap_fifo", "fifo_status", 1),
	Port_Property("event_queue_full_stream_write", 1, hls_out, 1, "ap_fifo", "fifo_data", 1),
	Port_Property("anti_message_stream_dout", 129, hls_in, 2, "ap_fifo", "fifo_port_we", 1),
	Port_Property("anti_message_stream_empty_n", 1, hls_in, 2, "ap_fifo", "fifo_status", 1),
	Port_Property("anti_message_stream_read", 1, hls_out, 2, "ap_fifo", "fifo_data", 1),
	Port_Property("enqueue_event_stream_dout", 129, hls_in, 3, "ap_fifo", "fifo_port_we", 1),
	Port_Property("enqueue_event_stream_empty_n", 1, hls_in, 3, "ap_fifo", "fifo_status", 1),
	Port_Property("enqueue_event_stream_read", 1, hls_out, 3, "ap_fifo", "fifo_data", 1),
	Port_Property("output_event_stream_din", 129, hls_out, 4, "ap_fifo", "fifo_port_we", 1),
	Port_Property("output_event_stream_full_n", 1, hls_in, 4, "ap_fifo", "fifo_status", 1),
	Port_Property("output_event_stream_write", 1, hls_out, 4, "ap_fifo", "fifo_data", 1),
	Port_Property("cancellation_unit_output_stream_din", 129, hls_out, 5, "ap_fifo", "fifo_port_we", 1),
	Port_Property("cancellation_unit_output_stream_full_n", 1, hls_in, 5, "ap_fifo", "fifo_status", 1),
	Port_Property("cancellation_unit_output_stream_write", 1, hls_out, 5, "ap_fifo", "fifo_data", 1),
	Port_Property("lpcore_commit_time_stream_dout", 32, hls_in, 6, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lpcore_commit_time_stream_empty_n", 1, hls_in, 6, "ap_fifo", "fifo_status", 1),
	Port_Property("lpcore_commit_time_stream_read", 1, hls_out, 6, "ap_fifo", "fifo_data", 1),
};
const char* HLS_Design_Meta::dut_name = "lpcore_top";
