// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="state_buffer_kernel_state_buffer_kernel,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvf1517-3-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.505000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=593,HLS_SYN_LUT=1244,HLS_VERSION=2022_1}" *)

module state_buffer_kernel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        op,
        state,
        result_i,
        result_o,
        result_i_ap_vld,
        result_o_ap_vld,
        success,
        success_ap_vld
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [1:0] op;
input  [95:0] state;
input  [79:0] result_i;
output  [79:0] result_o;
input   result_i_ap_vld;
output   result_o_ap_vld;
output   success;
output   success_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[79:0] result_o;
reg result_o_ap_vld;
reg success;
reg success_ap_vld;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [79:0] result_i_preg;
reg   [79:0] result_i_in_sig;
reg    result_i_ap_vld_preg;
reg    result_i_ap_vld_in_sig;
reg   [15:0] list_total_size_V;
reg   [15:0] list_free_head_V;
reg   [6:0] list_nodes_next_V_address0;
reg    list_nodes_next_V_ce0;
reg    list_nodes_next_V_we0;
reg   [15:0] list_nodes_next_V_d0;
wire   [15:0] list_nodes_next_V_q0;
reg   [6:0] list_nodes_state_lp_id_V_address0;
reg    list_nodes_state_lp_id_V_ce0;
reg    list_nodes_state_lp_id_V_we0;
wire   [15:0] list_nodes_state_lp_id_V_q0;
reg   [6:0] list_nodes_state_lvt_V_address0;
reg    list_nodes_state_lvt_V_ce0;
reg    list_nodes_state_lvt_V_we0;
wire   [31:0] list_nodes_state_lvt_V_d0;
wire   [31:0] list_nodes_state_lvt_V_q0;
reg   [6:0] list_nodes_state_rng_state_V_address0;
reg    list_nodes_state_rng_state_V_ce0;
reg    list_nodes_state_rng_state_V_we0;
wire   [31:0] list_nodes_state_rng_state_V_d0;
wire   [31:0] list_nodes_state_rng_state_V_q0;
reg   [5:0] list_lp_heads_V_address0;
reg    list_lp_heads_V_ce0;
reg    list_lp_heads_V_we0;
reg   [15:0] list_lp_heads_V_d0;
wire   [15:0] list_lp_heads_V_q0;
reg   [5:0] list_lp_sizes_V_address0;
reg    list_lp_sizes_V_ce0;
reg    list_lp_sizes_V_we0;
reg   [15:0] list_lp_sizes_V_d0;
wire   [15:0] list_lp_sizes_V_q0;
reg   [15:0] reg_425;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state12;
wire   [1:0] op_read_read_fu_144_p2;
wire   [15:0] state_lp_id_V_fu_431_p1;
reg   [15:0] state_lp_id_V_reg_720;
wire   [31:0] grp_fu_398_p4;
reg   [31:0] commit_time_V_reg_725;
reg   [15:0] list_total_size_V_load_reg_731;
wire   [63:0] zext_ln587_3_fu_465_p1;
reg   [63:0] zext_ln587_3_reg_752;
reg   [5:0] list_lp_sizes_V_addr_reg_757;
wire   [0:0] icmp_ln1077_fu_480_p2;
reg   [0:0] icmp_ln1077_reg_762;
reg   [6:0] list_nodes_next_V_addr_reg_766;
reg   [5:0] list_lp_sizes_V_addr_1_reg_776;
wire   [63:0] zext_ln587_2_fu_516_p1;
reg   [63:0] zext_ln587_2_reg_781;
wire   [5:0] trunc_ln95_fu_541_p1;
reg   [5:0] trunc_ln95_reg_794;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln1073_fu_524_p2;
reg   [5:0] list_lp_heads_V_addr_2_reg_807;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln1065_fu_579_p2;
wire    ap_CS_fsm_state7;
wire   [5:0] trunc_ln150_fu_658_p1;
reg   [5:0] trunc_ln150_reg_832;
wire    ap_CS_fsm_state13;
wire   [0:0] icmp_ln1081_fu_665_p2;
reg   [0:0] icmp_ln1081_reg_840;
wire    ap_CS_fsm_state15;
reg   [5:0] list_lp_sizes_V_addr_2_reg_844;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_start;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_done;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_idle;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_ready;
wire   [15:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_removed_V_3_out_o;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_removed_V_3_out_o_ap_vld;
wire   [6:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_next_V_address0;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_next_V_ce0;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_next_V_we0;
wire   [15:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_next_V_d0;
wire   [6:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_state_lvt_V_address0;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_state_lvt_V_ce0;
wire   [15:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_free_head_V_o;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_free_head_V_o_ap_vld;
wire   [5:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_sizes_V_address0;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_sizes_V_ce0;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_sizes_V_we0;
wire   [15:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_sizes_V_d0;
wire   [5:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_heads_V_address0;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_heads_V_ce0;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_heads_V_we0;
wire   [15:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_heads_V_d0;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_start;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_done;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_idle;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_ready;
wire   [15:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_removed_V_out;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_removed_V_out_ap_vld;
wire   [6:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_next_V_address0;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_next_V_ce0;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_next_V_we0;
wire   [15:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_next_V_d0;
wire   [5:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_lp_heads_V_address0;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_lp_heads_V_ce0;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_lp_heads_V_we0;
wire   [15:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_lp_heads_V_d0;
wire   [15:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_free_head_V_o;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_free_head_V_o_ap_vld;
wire   [6:0] grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_state_lvt_V_address0;
wire    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_state_lvt_V_ce0;
reg   [0:0] retval_0_i69_reg_323;
wire    ap_CS_fsm_state8;
reg   [0:0] retval_0_i_reg_337;
wire    ap_CS_fsm_state10;
reg   [0:0] ap_phi_mux_retval_0_i91_phi_fu_355_p4;
reg   [0:0] retval_0_i91_reg_351;
wire    ap_CS_fsm_state16;
reg    ap_block_state16;
reg    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [15:0] removed_V_1_fu_130;
reg    grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_start_reg;
wire    ap_CS_fsm_state14;
reg   [15:0] removed_V_loc_fu_126;
wire   [63:0] zext_ln587_fu_486_p1;
wire   [63:0] zext_ln587_4_fu_494_p1;
wire   [63:0] zext_ln1073_fu_536_p1;
wire   [63:0] zext_ln587_1_fu_603_p1;
wire   [15:0] sub_ln887_2_fu_671_p2;
wire   [15:0] add_ln887_1_fu_592_p2;
wire   [15:0] sub_ln887_fu_553_p2;
wire   [15:0] zext_ln886_fu_506_p1;
reg    ap_block_state2;
reg   [6:0] lp_id_V_1_fu_134;
wire   [6:0] add_ln886_2_fu_530_p2;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state11;
wire   [79:0] or_ln_fu_568_p4;
wire   [79:0] or_ln79_1_fu_617_p4;
wire   [79:0] or_ln16_1_fu_650_p3;
wire   [79:0] or_ln1_fu_692_p4;
wire   [15:0] add_ln887_fu_585_p2;
wire   [15:0] add_ln886_fu_634_p2;
wire   [15:0] sub_ln887_1_fu_682_p2;
wire   [8:0] tmp_1_fu_470_p4;
wire   [7:0] trunc_ln13_fu_451_p1;
wire   [7:0] add_ln886_1_fu_500_p2;
wire   [31:0] grp_fu_415_p4;
wire   [15:0] trunc_ln23_fu_564_p1;
wire   [63:0] tmp_fu_641_p4;
wire   [15:0] trunc_ln27_fu_688_p1;
reg   [15:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 result_i_preg = 80'd0;
#0 result_i_ap_vld_preg = 1'b0;
#0 list_total_size_V = 16'd0;
#0 list_free_head_V = 16'd0;
#0 grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_start_reg = 1'b0;
#0 grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_start_reg = 1'b0;
end

state_buffer_kernel_list_nodes_next_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
list_nodes_next_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(list_nodes_next_V_address0),
    .ce0(list_nodes_next_V_ce0),
    .we0(list_nodes_next_V_we0),
    .d0(list_nodes_next_V_d0),
    .q0(list_nodes_next_V_q0)
);

state_buffer_kernel_list_nodes_state_lp_id_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
list_nodes_state_lp_id_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(list_nodes_state_lp_id_V_address0),
    .ce0(list_nodes_state_lp_id_V_ce0),
    .we0(list_nodes_state_lp_id_V_we0),
    .d0(state_lp_id_V_fu_431_p1),
    .q0(list_nodes_state_lp_id_V_q0)
);

state_buffer_kernel_list_nodes_state_lvt_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
list_nodes_state_lvt_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(list_nodes_state_lvt_V_address0),
    .ce0(list_nodes_state_lvt_V_ce0),
    .we0(list_nodes_state_lvt_V_we0),
    .d0(list_nodes_state_lvt_V_d0),
    .q0(list_nodes_state_lvt_V_q0)
);

state_buffer_kernel_list_nodes_state_lvt_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
list_nodes_state_rng_state_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(list_nodes_state_rng_state_V_address0),
    .ce0(list_nodes_state_rng_state_V_ce0),
    .we0(list_nodes_state_rng_state_V_we0),
    .d0(list_nodes_state_rng_state_V_d0),
    .q0(list_nodes_state_rng_state_V_q0)
);

state_buffer_kernel_list_lp_heads_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
list_lp_heads_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(list_lp_heads_V_address0),
    .ce0(list_lp_heads_V_ce0),
    .we0(list_lp_heads_V_we0),
    .d0(list_lp_heads_V_d0),
    .q0(list_lp_heads_V_q0)
);

state_buffer_kernel_list_lp_sizes_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
list_lp_sizes_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(list_lp_sizes_V_address0),
    .ce0(list_lp_sizes_V_ce0),
    .we0(list_lp_sizes_V_we0),
    .d0(list_lp_sizes_V_d0),
    .q0(list_lp_sizes_V_q0)
);

state_buffer_kernel_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2 grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_start),
    .ap_done(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_done),
    .ap_idle(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_idle),
    .ap_ready(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_ready),
    .current_V_2(reg_425),
    .zext_ln1073(trunc_ln95_reg_794),
    .commit_time_V(commit_time_V_reg_725),
    .removed_V_3_out_i(removed_V_1_fu_130),
    .removed_V_3_out_o(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_removed_V_3_out_o),
    .removed_V_3_out_o_ap_vld(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_removed_V_3_out_o_ap_vld),
    .list_nodes_next_V_address0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_next_V_address0),
    .list_nodes_next_V_ce0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_next_V_ce0),
    .list_nodes_next_V_we0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_next_V_we0),
    .list_nodes_next_V_d0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_next_V_d0),
    .list_nodes_next_V_q0(list_nodes_next_V_q0),
    .list_nodes_state_lvt_V_address0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_state_lvt_V_address0),
    .list_nodes_state_lvt_V_ce0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_state_lvt_V_ce0),
    .list_nodes_state_lvt_V_q0(list_nodes_state_lvt_V_q0),
    .list_free_head_V_i(list_free_head_V),
    .list_free_head_V_o(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_free_head_V_o),
    .list_free_head_V_o_ap_vld(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_free_head_V_o_ap_vld),
    .list_lp_sizes_V_address0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_sizes_V_address0),
    .list_lp_sizes_V_ce0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_sizes_V_ce0),
    .list_lp_sizes_V_we0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_sizes_V_we0),
    .list_lp_sizes_V_d0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_sizes_V_d0),
    .list_lp_sizes_V_q0(list_lp_sizes_V_q0),
    .list_lp_heads_V_address0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_heads_V_address0),
    .list_lp_heads_V_ce0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_heads_V_ce0),
    .list_lp_heads_V_we0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_heads_V_we0),
    .list_lp_heads_V_d0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_heads_V_d0)
);

state_buffer_kernel_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1 grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_start),
    .ap_done(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_done),
    .ap_idle(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_idle),
    .ap_ready(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_ready),
    .current_V(reg_425),
    .zext_ln587_5(trunc_ln150_reg_832),
    .commit_time_V(commit_time_V_reg_725),
    .removed_V_out(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_removed_V_out),
    .removed_V_out_ap_vld(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_removed_V_out_ap_vld),
    .list_nodes_next_V_address0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_next_V_address0),
    .list_nodes_next_V_ce0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_next_V_ce0),
    .list_nodes_next_V_we0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_next_V_we0),
    .list_nodes_next_V_d0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_next_V_d0),
    .list_nodes_next_V_q0(list_nodes_next_V_q0),
    .list_lp_heads_V_address0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_lp_heads_V_address0),
    .list_lp_heads_V_ce0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_lp_heads_V_ce0),
    .list_lp_heads_V_we0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_lp_heads_V_we0),
    .list_lp_heads_V_d0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_lp_heads_V_d0),
    .list_free_head_V_i(list_free_head_V),
    .list_free_head_V_o(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_free_head_V_o),
    .list_free_head_V_o_ap_vld(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_free_head_V_o_ap_vld),
    .list_nodes_state_lvt_V_address0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_state_lvt_V_address0),
    .list_nodes_state_lvt_V_ce0(grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_state_lvt_V_ce0),
    .list_nodes_state_lvt_V_q0(list_nodes_state_lvt_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_start_reg <= 1'b1;
        end else if ((grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_ready == 1'b1)) begin
            grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_start_reg <= 1'b1;
        end else if ((grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_ready == 1'b1)) begin
            grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        result_i_ap_vld_preg <= 1'b0;
    end else begin
        if ((~((result_i_ap_vld_in_sig == 1'b0) & (op == 2'd3)) & (1'b1 == ap_CS_fsm_state16))) begin
            result_i_ap_vld_preg <= 1'b0;
        end else if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (result_i_ap_vld == 1'b1))) begin
            result_i_ap_vld_preg <= result_i_ap_vld;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        result_i_preg <= 80'd0;
    end else begin
        if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (result_i_ap_vld == 1'b1))) begin
            result_i_preg <= result_i;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        list_free_head_V <= list_lp_heads_V_q0;
    end else if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln1077_reg_762 == 1'd1))) begin
        list_free_head_V <= list_nodes_next_V_q0;
    end else if (((grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_free_head_V_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        list_free_head_V <= grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_free_head_V_o;
    end else if (((grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_free_head_V_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        list_free_head_V <= grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_free_head_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1077_fu_480_p2 == 1'd1) & (op_read_read_fu_144_p2 == 2'd0))) begin
        list_total_size_V <= zext_ln886_fu_506_p1;
    end else if ((~((result_i_ap_vld_in_sig == 1'b0) & (icmp_ln1073_fu_524_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln1073_fu_524_p2 == 1'd1))) begin
        list_total_size_V <= sub_ln887_fu_553_p2;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln1065_fu_579_p2 == 1'd0))) begin
        list_total_size_V <= add_ln887_1_fu_592_p2;
    end else if (((icmp_ln1081_fu_665_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
        list_total_size_V <= sub_ln887_2_fu_671_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (op_read_read_fu_144_p2 == 2'd2))) begin
        lp_id_V_1_fu_134 <= 7'd0;
    end else if ((~((result_i_ap_vld_in_sig == 1'b0) & (icmp_ln1073_fu_524_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln1073_fu_524_p2 == 1'd0))) begin
        lp_id_V_1_fu_134 <= add_ln886_2_fu_530_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (op_read_read_fu_144_p2 == 2'd2))) begin
        removed_V_1_fu_130 <= 16'd0;
    end else if (((grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_removed_V_3_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        removed_V_1_fu_130 <= grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_removed_V_3_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln1065_fu_579_p2 == 1'd1))) begin
        retval_0_i69_reg_323 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        retval_0_i69_reg_323 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1081_fu_665_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        retval_0_i91_reg_351 <= 1'd0;
    end else if ((~((result_i_ap_vld_in_sig == 1'b0) & (op == 2'd3)) & (icmp_ln1081_reg_840 == 1'd0) & (1'b1 == ap_CS_fsm_state16) & (op == 2'd3))) begin
        retval_0_i91_reg_351 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1077_fu_480_p2 == 1'd0) & (op_read_read_fu_144_p2 == 2'd0))) begin
        retval_0_i_reg_337 <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln1077_reg_762 == 1'd1))) begin
        retval_0_i_reg_337 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        commit_time_V_reg_725 <= {{state[63:32]}};
        list_total_size_V_load_reg_731 <= list_total_size_V;
        state_lp_id_V_reg_720 <= state_lp_id_V_fu_431_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (op_read_read_fu_144_p2 == 2'd0))) begin
        icmp_ln1077_reg_762 <= icmp_ln1077_fu_480_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        icmp_ln1081_reg_840 <= icmp_ln1081_fu_665_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln1065_fu_579_p2 == 1'd0))) begin
        list_lp_heads_V_addr_2_reg_807 <= zext_ln587_3_reg_752;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln1077_fu_480_p2 == 1'd1) & (op_read_read_fu_144_p2 == 2'd0))) begin
        list_lp_sizes_V_addr_1_reg_776 <= zext_ln587_4_fu_494_p1;
        list_nodes_next_V_addr_reg_766 <= zext_ln587_fu_486_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1081_fu_665_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
        list_lp_sizes_V_addr_2_reg_844 <= zext_ln587_2_reg_781;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (op_read_read_fu_144_p2 == 2'd1))) begin
        list_lp_sizes_V_addr_reg_757 <= zext_ln587_3_fu_465_p1;
        zext_ln587_3_reg_752[15 : 0] <= zext_ln587_3_fu_465_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state3))) begin
        reg_425 <= list_lp_heads_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_removed_V_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        removed_V_loc_fu_126 <= grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_removed_V_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        trunc_ln150_reg_832 <= trunc_ln150_fu_658_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1073_fu_524_p2 == 1'd0))) begin
        trunc_ln95_reg_794 <= trunc_ln95_fu_541_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (op == 2'd3))) begin
        zext_ln587_2_reg_781[15 : 0] <= zext_ln587_2_fu_516_p1[15 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if (((result_i_ap_vld_in_sig == 1'b0) & (op == 2'd3))) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((result_i_ap_vld_in_sig == 1'b0) & (icmp_ln1073_fu_524_p2 == 1'd1))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((~((result_i_ap_vld_in_sig == 1'b0) & (op == 2'd3)) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1081_reg_840 == 1'd0) & (1'b1 == ap_CS_fsm_state16) & (op == 2'd3))) begin
        ap_phi_mux_retval_0_i91_phi_fu_355_p4 = 1'd1;
    end else begin
        ap_phi_mux_retval_0_i91_phi_fu_355_p4 = retval_0_i91_reg_351;
    end
end

always @ (*) begin
    if ((~((result_i_ap_vld_in_sig == 1'b0) & (op == 2'd3)) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        list_lp_heads_V_address0 = list_lp_heads_V_addr_2_reg_807;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        list_lp_heads_V_address0 = zext_ln587_3_reg_752;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        list_lp_heads_V_address0 = zext_ln1073_fu_536_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (op == 2'd3))) begin
        list_lp_heads_V_address0 = zext_ln587_2_fu_516_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln1077_fu_480_p2 == 1'd1) & (op_read_read_fu_144_p2 == 2'd0))) begin
        list_lp_heads_V_address0 = zext_ln587_4_fu_494_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        list_lp_heads_V_address0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_lp_heads_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_lp_heads_V_address0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_heads_V_address0;
    end else begin
        list_lp_heads_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (~((result_i_ap_vld_in_sig == 1'b0) & (icmp_ln1073_fu_524_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (op == 2'd3)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1077_fu_480_p2 == 1'd1) & (op_read_read_fu_144_p2 == 2'd0)))) begin
        list_lp_heads_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        list_lp_heads_V_ce0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_lp_heads_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_lp_heads_V_ce0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_heads_V_ce0;
    end else begin
        list_lp_heads_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        list_lp_heads_V_d0 = list_nodes_next_V_q0;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln1077_fu_480_p2 == 1'd1) & (op_read_read_fu_144_p2 == 2'd0))) begin
        list_lp_heads_V_d0 = list_free_head_V;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        list_lp_heads_V_d0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_lp_heads_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_lp_heads_V_d0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_heads_V_d0;
    end else begin
        list_lp_heads_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1077_fu_480_p2 == 1'd1) & (op_read_read_fu_144_p2 == 2'd0)))) begin
        list_lp_heads_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        list_lp_heads_V_we0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_lp_heads_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_lp_heads_V_we0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_heads_V_we0;
    end else begin
        list_lp_heads_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        list_lp_sizes_V_address0 = list_lp_sizes_V_addr_2_reg_844;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        list_lp_sizes_V_address0 = zext_ln587_2_reg_781;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        list_lp_sizes_V_address0 = list_lp_sizes_V_addr_1_reg_776;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        list_lp_sizes_V_address0 = list_lp_sizes_V_addr_reg_757;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln1077_fu_480_p2 == 1'd1) & (op_read_read_fu_144_p2 == 2'd0))) begin
        list_lp_sizes_V_address0 = zext_ln587_4_fu_494_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (op_read_read_fu_144_p2 == 2'd1))) begin
        list_lp_sizes_V_address0 = zext_ln587_3_fu_465_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_lp_sizes_V_address0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_sizes_V_address0;
    end else begin
        list_lp_sizes_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state6) | (~((result_i_ap_vld_in_sig == 1'b0) & (op == 2'd3)) & (1'b1 == ap_CS_fsm_state16)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1077_fu_480_p2 == 1'd1) & (op_read_read_fu_144_p2 == 2'd0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (op_read_read_fu_144_p2 == 2'd1)))) begin
        list_lp_sizes_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_lp_sizes_V_ce0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_sizes_V_ce0;
    end else begin
        list_lp_sizes_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        list_lp_sizes_V_d0 = sub_ln887_1_fu_682_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        list_lp_sizes_V_d0 = add_ln886_fu_634_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        list_lp_sizes_V_d0 = add_ln887_fu_585_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_lp_sizes_V_d0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_sizes_V_d0;
    end else begin
        list_lp_sizes_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((~((result_i_ap_vld_in_sig == 1'b0) & (op == 2'd3)) & (icmp_ln1081_reg_840 == 1'd0) & (1'b1 == ap_CS_fsm_state16) & (op == 2'd3)) | ((1'b1 == ap_CS_fsm_state10) & (icmp_ln1077_reg_762 == 1'd1)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln1065_fu_579_p2 == 1'd0)))) begin
        list_lp_sizes_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_lp_sizes_V_we0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_lp_sizes_V_we0;
    end else begin
        list_lp_sizes_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        list_nodes_next_V_address0 = list_nodes_next_V_addr_reg_766;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        list_nodes_next_V_address0 = zext_ln587_1_fu_603_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        list_nodes_next_V_address0 = zext_ln587_fu_486_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        list_nodes_next_V_address0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_next_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_nodes_next_V_address0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_next_V_address0;
    end else begin
        list_nodes_next_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        list_nodes_next_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        list_nodes_next_V_ce0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_next_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_nodes_next_V_ce0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_next_V_ce0;
    end else begin
        list_nodes_next_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        list_nodes_next_V_d0 = list_lp_heads_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        list_nodes_next_V_d0 = list_free_head_V;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        list_nodes_next_V_d0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_next_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_nodes_next_V_d0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_next_V_d0;
    end else begin
        list_nodes_next_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state10) & (icmp_ln1077_reg_762 == 1'd1)))) begin
        list_nodes_next_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        list_nodes_next_V_we0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_next_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_nodes_next_V_we0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_next_V_we0;
    end else begin
        list_nodes_next_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        list_nodes_state_lp_id_V_address0 = zext_ln587_1_fu_603_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        list_nodes_state_lp_id_V_address0 = zext_ln587_fu_486_p1;
    end else begin
        list_nodes_state_lp_id_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        list_nodes_state_lp_id_V_ce0 = 1'b1;
    end else begin
        list_nodes_state_lp_id_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1077_fu_480_p2 == 1'd1) & (op_read_read_fu_144_p2 == 2'd0))) begin
        list_nodes_state_lp_id_V_we0 = 1'b1;
    end else begin
        list_nodes_state_lp_id_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        list_nodes_state_lvt_V_address0 = zext_ln587_1_fu_603_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        list_nodes_state_lvt_V_address0 = zext_ln587_fu_486_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        list_nodes_state_lvt_V_address0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_state_lvt_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_nodes_state_lvt_V_address0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_state_lvt_V_address0;
    end else begin
        list_nodes_state_lvt_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        list_nodes_state_lvt_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        list_nodes_state_lvt_V_ce0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_list_nodes_state_lvt_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        list_nodes_state_lvt_V_ce0 = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_list_nodes_state_lvt_V_ce0;
    end else begin
        list_nodes_state_lvt_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1077_fu_480_p2 == 1'd1) & (op_read_read_fu_144_p2 == 2'd0))) begin
        list_nodes_state_lvt_V_we0 = 1'b1;
    end else begin
        list_nodes_state_lvt_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        list_nodes_state_rng_state_V_address0 = zext_ln587_1_fu_603_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        list_nodes_state_rng_state_V_address0 = zext_ln587_fu_486_p1;
    end else begin
        list_nodes_state_rng_state_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        list_nodes_state_rng_state_V_ce0 = 1'b1;
    end else begin
        list_nodes_state_rng_state_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1077_fu_480_p2 == 1'd1) & (op_read_read_fu_144_p2 == 2'd0))) begin
        list_nodes_state_rng_state_V_we0 = 1'b1;
    end else begin
        list_nodes_state_rng_state_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((result_i_ap_vld == 1'b1)) begin
        result_i_ap_vld_in_sig = result_i_ap_vld;
    end else begin
        result_i_ap_vld_in_sig = result_i_ap_vld_preg;
    end
end

always @ (*) begin
    if ((result_i_ap_vld == 1'b1)) begin
        result_i_in_sig = result_i;
    end else begin
        result_i_in_sig = result_i_preg;
    end
end

always @ (*) begin
    if ((~((result_i_ap_vld_in_sig == 1'b0) & (op == 2'd3)) & (1'b1 == ap_CS_fsm_state16) & (op == 2'd3))) begin
        result_o = or_ln1_fu_692_p4;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        result_o = or_ln16_1_fu_650_p3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        result_o = or_ln79_1_fu_617_p4;
    end else if ((~((result_i_ap_vld_in_sig == 1'b0) & (icmp_ln1073_fu_524_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln1073_fu_524_p2 == 1'd1))) begin
        result_o = or_ln_fu_568_p4;
    end else begin
        result_o = result_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (~((result_i_ap_vld_in_sig == 1'b0) & (icmp_ln1073_fu_524_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln1073_fu_524_p2 == 1'd1)) | (~((result_i_ap_vld_in_sig == 1'b0) & (op == 2'd3)) & (1'b1 == ap_CS_fsm_state16) & (op == 2'd3)))) begin
        result_o_ap_vld = 1'b1;
    end else begin
        result_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((result_i_ap_vld_in_sig == 1'b0) & (op == 2'd3)) & (1'b1 == ap_CS_fsm_state16) & (op == 2'd3))) begin
        success = ap_phi_mux_retval_0_i91_phi_fu_355_p4;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        success = retval_0_i_reg_337;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        success = retval_0_i69_reg_323;
    end else if ((~((result_i_ap_vld_in_sig == 1'b0) & (icmp_ln1073_fu_524_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln1073_fu_524_p2 == 1'd1))) begin
        success = 1'd1;
    end else begin
        success = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state9) | (~((result_i_ap_vld_in_sig == 1'b0) & (icmp_ln1073_fu_524_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln1073_fu_524_p2 == 1'd1)) | (~((result_i_ap_vld_in_sig == 1'b0) & (op == 2'd3)) & (1'b1 == ap_CS_fsm_state16) & (op == 2'd3)))) begin
        success_ap_vld = 1'b1;
    end else begin
        success_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (op_read_read_fu_144_p2 == 2'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (op_read_read_fu_144_p2 == 2'd2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (op == 2'd3))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (op_read_read_fu_144_p2 == 2'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((result_i_ap_vld_in_sig == 1'b0) & (icmp_ln1073_fu_524_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln1073_fu_524_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if ((~((result_i_ap_vld_in_sig == 1'b0) & (icmp_ln1073_fu_524_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln1073_fu_524_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln1065_fu_579_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if ((~((result_i_ap_vld_in_sig == 1'b0) & (op == 2'd3)) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln886_1_fu_500_p2 = (trunc_ln13_fu_451_p1 + 8'd1);

assign add_ln886_2_fu_530_p2 = (lp_id_V_1_fu_134 + 7'd1);

assign add_ln886_fu_634_p2 = (list_lp_sizes_V_q0 + 16'd1);

assign add_ln887_1_fu_592_p2 = ($signed(list_total_size_V_load_reg_731) + $signed(16'd65535));

assign add_ln887_fu_585_p2 = ($signed(list_lp_sizes_V_q0) + $signed(16'd65535));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state16 = ((result_i_ap_vld_in_sig == 1'b0) & (op == 2'd3));
end

always @ (*) begin
    ap_block_state2 = ((result_i_ap_vld_in_sig == 1'b0) & (icmp_ln1073_fu_524_p2 == 1'd1));
end

assign grp_fu_398_p4 = {{state[63:32]}};

assign grp_fu_415_p4 = {{result_i_in_sig[79:48]}};

assign grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_start = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2_fu_364_ap_start_reg;

assign grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_start = grp_state_buffer_kernel_Pipeline_VITIS_LOOP_154_1_fu_382_ap_start_reg;

assign icmp_ln1065_fu_579_p2 = ((list_lp_sizes_V_q0 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1073_fu_524_p2 = ((lp_id_V_1_fu_134 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln1077_fu_480_p2 = ((tmp_1_fu_470_p4 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1081_fu_665_p2 = ((removed_V_loc_fu_126 == 16'd0) ? 1'b1 : 1'b0);

assign list_nodes_state_lvt_V_d0 = {{state[63:32]}};

assign list_nodes_state_rng_state_V_d0 = {{state[95:64]}};

assign op_read_read_fu_144_p2 = op;

assign or_ln16_1_fu_650_p3 = {{tmp_fu_641_p4}, {state_lp_id_V_reg_720}};

assign or_ln1_fu_692_p4 = {{{grp_fu_415_p4}, {grp_fu_398_p4}}, {trunc_ln27_fu_688_p1}};

assign or_ln79_1_fu_617_p4 = {{{list_nodes_state_rng_state_V_q0}, {list_nodes_state_lvt_V_q0}}, {list_nodes_state_lp_id_V_q0}};

assign or_ln_fu_568_p4 = {{{grp_fu_415_p4}, {grp_fu_398_p4}}, {trunc_ln23_fu_564_p1}};

assign state_lp_id_V_fu_431_p1 = state[15:0];

assign sub_ln887_1_fu_682_p2 = (list_lp_sizes_V_q0 - removed_V_loc_fu_126);

assign sub_ln887_2_fu_671_p2 = (list_total_size_V_load_reg_731 - removed_V_loc_fu_126);

assign sub_ln887_fu_553_p2 = (list_total_size_V_load_reg_731 - removed_V_1_fu_130);

assign tmp_1_fu_470_p4 = {{list_total_size_V[15:7]}};

assign tmp_fu_641_p4 = {{state[95:32]}};

assign trunc_ln13_fu_451_p1 = list_total_size_V[7:0];

assign trunc_ln150_fu_658_p1 = state[5:0];

assign trunc_ln23_fu_564_p1 = result_i_in_sig[15:0];

assign trunc_ln27_fu_688_p1 = result_i_in_sig[15:0];

assign trunc_ln95_fu_541_p1 = lp_id_V_1_fu_134[5:0];

assign zext_ln1073_fu_536_p1 = lp_id_V_1_fu_134;

assign zext_ln587_1_fu_603_p1 = list_lp_heads_V_q0;

assign zext_ln587_2_fu_516_p1 = state_lp_id_V_fu_431_p1;

assign zext_ln587_3_fu_465_p1 = state_lp_id_V_fu_431_p1;

assign zext_ln587_4_fu_494_p1 = state_lp_id_V_fu_431_p1;

assign zext_ln587_fu_486_p1 = list_free_head_V;

assign zext_ln886_fu_506_p1 = add_ln886_1_fu_500_p2;

always @ (posedge ap_clk) begin
    zext_ln587_3_reg_752[63:16] <= 48'b000000000000000000000000000000000000000000000000;
    zext_ln587_2_reg_781[63:16] <= 48'b000000000000000000000000000000000000000000000000;
end

endmodule //state_buffer_kernel
