// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module simulation_top_event_router_top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        lpcore_output_event_stream_0_dout,
        lpcore_output_event_stream_0_num_data_valid,
        lpcore_output_event_stream_0_fifo_cap,
        lpcore_output_event_stream_0_empty_n,
        lpcore_output_event_stream_0_read,
        lpcore_output_event_stream_1_dout,
        lpcore_output_event_stream_1_num_data_valid,
        lpcore_output_event_stream_1_fifo_cap,
        lpcore_output_event_stream_1_empty_n,
        lpcore_output_event_stream_1_read,
        lpcore_cancellation_unit_output_stream_0_dout,
        lpcore_cancellation_unit_output_stream_0_num_data_valid,
        lpcore_cancellation_unit_output_stream_0_fifo_cap,
        lpcore_cancellation_unit_output_stream_0_empty_n,
        lpcore_cancellation_unit_output_stream_0_read,
        lpcore_cancellation_unit_output_stream_1_dout,
        lpcore_cancellation_unit_output_stream_1_num_data_valid,
        lpcore_cancellation_unit_output_stream_1_fifo_cap,
        lpcore_cancellation_unit_output_stream_1_empty_n,
        lpcore_cancellation_unit_output_stream_1_read,
        lpcore_enqueue_event_stream_0_din,
        lpcore_enqueue_event_stream_0_num_data_valid,
        lpcore_enqueue_event_stream_0_fifo_cap,
        lpcore_enqueue_event_stream_0_full_n,
        lpcore_enqueue_event_stream_0_write,
        lpcore_enqueue_event_stream_1_din,
        lpcore_enqueue_event_stream_1_num_data_valid,
        lpcore_enqueue_event_stream_1_fifo_cap,
        lpcore_enqueue_event_stream_1_full_n,
        lpcore_enqueue_event_stream_1_write,
        lpcore_anti_message_stream_0_din,
        lpcore_anti_message_stream_0_num_data_valid,
        lpcore_anti_message_stream_0_fifo_cap,
        lpcore_anti_message_stream_0_full_n,
        lpcore_anti_message_stream_0_write,
        lpcore_anti_message_stream_1_din,
        lpcore_anti_message_stream_1_num_data_valid,
        lpcore_anti_message_stream_1_fifo_cap,
        lpcore_anti_message_stream_1_full_n,
        lpcore_anti_message_stream_1_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [128:0] lpcore_output_event_stream_0_dout;
input  [1:0] lpcore_output_event_stream_0_num_data_valid;
input  [1:0] lpcore_output_event_stream_0_fifo_cap;
input   lpcore_output_event_stream_0_empty_n;
output   lpcore_output_event_stream_0_read;
input  [128:0] lpcore_output_event_stream_1_dout;
input  [1:0] lpcore_output_event_stream_1_num_data_valid;
input  [1:0] lpcore_output_event_stream_1_fifo_cap;
input   lpcore_output_event_stream_1_empty_n;
output   lpcore_output_event_stream_1_read;
input  [128:0] lpcore_cancellation_unit_output_stream_0_dout;
input  [1:0] lpcore_cancellation_unit_output_stream_0_num_data_valid;
input  [1:0] lpcore_cancellation_unit_output_stream_0_fifo_cap;
input   lpcore_cancellation_unit_output_stream_0_empty_n;
output   lpcore_cancellation_unit_output_stream_0_read;
input  [128:0] lpcore_cancellation_unit_output_stream_1_dout;
input  [1:0] lpcore_cancellation_unit_output_stream_1_num_data_valid;
input  [1:0] lpcore_cancellation_unit_output_stream_1_fifo_cap;
input   lpcore_cancellation_unit_output_stream_1_empty_n;
output   lpcore_cancellation_unit_output_stream_1_read;
output  [128:0] lpcore_enqueue_event_stream_0_din;
input  [1:0] lpcore_enqueue_event_stream_0_num_data_valid;
input  [1:0] lpcore_enqueue_event_stream_0_fifo_cap;
input   lpcore_enqueue_event_stream_0_full_n;
output   lpcore_enqueue_event_stream_0_write;
output  [128:0] lpcore_enqueue_event_stream_1_din;
input  [1:0] lpcore_enqueue_event_stream_1_num_data_valid;
input  [1:0] lpcore_enqueue_event_stream_1_fifo_cap;
input   lpcore_enqueue_event_stream_1_full_n;
output   lpcore_enqueue_event_stream_1_write;
output  [128:0] lpcore_anti_message_stream_0_din;
input  [1:0] lpcore_anti_message_stream_0_num_data_valid;
input  [1:0] lpcore_anti_message_stream_0_fifo_cap;
input   lpcore_anti_message_stream_0_full_n;
output   lpcore_anti_message_stream_0_write;
output  [128:0] lpcore_anti_message_stream_1_din;
input  [1:0] lpcore_anti_message_stream_1_num_data_valid;
input  [1:0] lpcore_anti_message_stream_1_fifo_cap;
input   lpcore_anti_message_stream_1_full_n;
output   lpcore_anti_message_stream_1_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg lpcore_output_event_stream_0_read;
reg lpcore_output_event_stream_1_read;
reg lpcore_cancellation_unit_output_stream_0_read;
reg lpcore_cancellation_unit_output_stream_1_read;
reg[128:0] lpcore_enqueue_event_stream_0_din;
reg lpcore_enqueue_event_stream_0_write;
reg[128:0] lpcore_enqueue_event_stream_1_din;
reg lpcore_enqueue_event_stream_1_write;
reg[128:0] lpcore_anti_message_stream_0_din;
reg lpcore_anti_message_stream_0_write;
reg[128:0] lpcore_anti_message_stream_1_din;
reg lpcore_anti_message_stream_1_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    lpcore_output_event_stream_0_blk_n;
wire   [0:0] tmp_nbreadreq_fu_38_p3;
reg    lpcore_output_event_stream_1_blk_n;
wire    ap_CS_fsm_state2;
reg   [0:0] tmp_2_reg_174;
reg    lpcore_cancellation_unit_output_stream_0_blk_n;
wire   [0:0] tmp_s_nbreadreq_fu_68_p3;
reg    lpcore_cancellation_unit_output_stream_1_blk_n;
wire   [0:0] tmp_3_nbreadreq_fu_114_p3;
reg    lpcore_enqueue_event_stream_0_blk_n;
wire   [0:0] tmp_19_fu_130_p3;
wire   [0:0] tmp_21_fu_146_p3;
reg    lpcore_enqueue_event_stream_1_blk_n;
reg    lpcore_anti_message_stream_0_blk_n;
wire   [0:0] tmp_20_fu_138_p3;
wire   [0:0] tmp_22_fu_154_p3;
reg    lpcore_anti_message_stream_1_blk_n;
wire   [0:0] tmp_2_nbreadreq_fu_98_p3;
reg    ap_predicate_op16_write_state1;
reg    ap_predicate_op18_write_state1;
reg    ap_predicate_op26_write_state1;
reg    ap_predicate_op28_write_state1;
reg    ap_block_state1;
reg    ap_predicate_op36_write_state2;
reg    ap_predicate_op38_write_state2;
reg    ap_predicate_op46_write_state2;
reg    ap_predicate_op48_write_state2;
reg    ap_block_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_2_reg_174 <= tmp_2_nbreadreq_fu_98_p3;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_0_empty_n == 1'b0)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (lpcore_output_event_stream_0_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op28_write_state1 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op26_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op18_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op16_write_state1 == 1'b1)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1)))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (tmp_22_fu_154_p3 == 1'd0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (tmp_20_fu_138_p3 == 1'd0)))) begin
        lpcore_anti_message_stream_0_blk_n = lpcore_anti_message_stream_0_full_n;
    end else begin
        lpcore_anti_message_stream_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2) & (ap_predicate_op46_write_state2 == 1'b1))) begin
        lpcore_anti_message_stream_0_din = lpcore_cancellation_unit_output_stream_1_dout;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_0_empty_n == 1'b0)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (lpcore_output_event_stream_0_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op28_write_state1 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op26_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op18_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op16_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op26_write_state1 == 1'b1))) begin
        lpcore_anti_message_stream_0_din = lpcore_cancellation_unit_output_stream_0_dout;
    end else begin
        lpcore_anti_message_stream_0_din = 'bx;
    end
end

always @ (*) begin
    if (((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2) & (ap_predicate_op46_write_state2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_0_empty_n == 1'b0)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (lpcore_output_event_stream_0_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op28_write_state1 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op26_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op18_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op16_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op26_write_state1 == 1'b1)))) begin
        lpcore_anti_message_stream_0_write = 1'b1;
    end else begin
        lpcore_anti_message_stream_0_write = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (tmp_22_fu_154_p3 == 1'd1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (tmp_20_fu_138_p3 == 1'd1)))) begin
        lpcore_anti_message_stream_1_blk_n = lpcore_anti_message_stream_1_full_n;
    end else begin
        lpcore_anti_message_stream_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2) & (ap_predicate_op48_write_state2 == 1'b1))) begin
        lpcore_anti_message_stream_1_din = lpcore_cancellation_unit_output_stream_1_dout;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_0_empty_n == 1'b0)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (lpcore_output_event_stream_0_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op28_write_state1 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op26_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op18_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op16_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op28_write_state1 == 1'b1))) begin
        lpcore_anti_message_stream_1_din = lpcore_cancellation_unit_output_stream_0_dout;
    end else begin
        lpcore_anti_message_stream_1_din = 'bx;
    end
end

always @ (*) begin
    if (((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2) & (ap_predicate_op48_write_state2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_0_empty_n == 1'b0)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (lpcore_output_event_stream_0_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op28_write_state1 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op26_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op18_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op16_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op28_write_state1 == 1'b1)))) begin
        lpcore_anti_message_stream_1_write = 1'b1;
    end else begin
        lpcore_anti_message_stream_1_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        lpcore_cancellation_unit_output_stream_0_blk_n = lpcore_cancellation_unit_output_stream_0_empty_n;
    end else begin
        lpcore_cancellation_unit_output_stream_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_0_empty_n == 1'b0)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (lpcore_output_event_stream_0_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op28_write_state1 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op26_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op18_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op16_write_state1 == 1'b1))) & (tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        lpcore_cancellation_unit_output_stream_0_read = 1'b1;
    end else begin
        lpcore_cancellation_unit_output_stream_0_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        lpcore_cancellation_unit_output_stream_1_blk_n = lpcore_cancellation_unit_output_stream_1_empty_n;
    end else begin
        lpcore_cancellation_unit_output_stream_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        lpcore_cancellation_unit_output_stream_1_read = 1'b1;
    end else begin
        lpcore_cancellation_unit_output_stream_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_reg_174 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (tmp_21_fu_146_p3 == 1'd0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_nbreadreq_fu_38_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (tmp_19_fu_130_p3 == 1'd0)))) begin
        lpcore_enqueue_event_stream_0_blk_n = lpcore_enqueue_event_stream_0_full_n;
    end else begin
        lpcore_enqueue_event_stream_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2) & (ap_predicate_op36_write_state2 == 1'b1))) begin
        lpcore_enqueue_event_stream_0_din = lpcore_output_event_stream_1_dout;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_0_empty_n == 1'b0)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (lpcore_output_event_stream_0_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op28_write_state1 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op26_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op18_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op16_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op16_write_state1 == 1'b1))) begin
        lpcore_enqueue_event_stream_0_din = lpcore_output_event_stream_0_dout;
    end else begin
        lpcore_enqueue_event_stream_0_din = 'bx;
    end
end

always @ (*) begin
    if (((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2) & (ap_predicate_op36_write_state2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_0_empty_n == 1'b0)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (lpcore_output_event_stream_0_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op28_write_state1 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op26_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op18_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op16_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op16_write_state1 == 1'b1)))) begin
        lpcore_enqueue_event_stream_0_write = 1'b1;
    end else begin
        lpcore_enqueue_event_stream_0_write = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_reg_174 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (tmp_21_fu_146_p3 == 1'd1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_nbreadreq_fu_38_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (tmp_19_fu_130_p3 == 1'd1)))) begin
        lpcore_enqueue_event_stream_1_blk_n = lpcore_enqueue_event_stream_1_full_n;
    end else begin
        lpcore_enqueue_event_stream_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2) & (ap_predicate_op38_write_state2 == 1'b1))) begin
        lpcore_enqueue_event_stream_1_din = lpcore_output_event_stream_1_dout;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_0_empty_n == 1'b0)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (lpcore_output_event_stream_0_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op28_write_state1 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op26_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op18_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op16_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op18_write_state1 == 1'b1))) begin
        lpcore_enqueue_event_stream_1_din = lpcore_output_event_stream_0_dout;
    end else begin
        lpcore_enqueue_event_stream_1_din = 'bx;
    end
end

always @ (*) begin
    if (((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2) & (ap_predicate_op38_write_state2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_0_empty_n == 1'b0)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (lpcore_output_event_stream_0_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op28_write_state1 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op26_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op18_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op16_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op18_write_state1 == 1'b1)))) begin
        lpcore_enqueue_event_stream_1_write = 1'b1;
    end else begin
        lpcore_enqueue_event_stream_1_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_nbreadreq_fu_38_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        lpcore_output_event_stream_0_blk_n = lpcore_output_event_stream_0_empty_n;
    end else begin
        lpcore_output_event_stream_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_0_empty_n == 1'b0)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (lpcore_output_event_stream_0_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op28_write_state1 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op26_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op18_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op16_write_state1 == 1'b1))) & (tmp_nbreadreq_fu_38_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        lpcore_output_event_stream_0_read = 1'b1;
    end else begin
        lpcore_output_event_stream_0_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_174 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        lpcore_output_event_stream_1_blk_n = lpcore_output_event_stream_1_empty_n;
    end else begin
        lpcore_output_event_stream_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (tmp_2_reg_174 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        lpcore_output_event_stream_1_read = 1'b1;
    end else begin
        lpcore_output_event_stream_1_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_0_empty_n == 1'b0)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (lpcore_output_event_stream_0_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op28_write_state1 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op26_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op18_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op16_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~(((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_0_empty_n == 1'b0)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (lpcore_output_event_stream_0_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op28_write_state1 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op26_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op18_write_state1 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op16_write_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state2 = (((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (lpcore_cancellation_unit_output_stream_1_empty_n == 1'b0)) | ((tmp_2_reg_174 == 1'd1) & (lpcore_output_event_stream_1_empty_n == 1'b0)) | ((lpcore_anti_message_stream_1_full_n == 1'b0) & (ap_predicate_op48_write_state2 == 1'b1)) | ((lpcore_anti_message_stream_0_full_n == 1'b0) & (ap_predicate_op46_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_1_full_n == 1'b0) & (ap_predicate_op38_write_state2 == 1'b1)) | ((lpcore_enqueue_event_stream_0_full_n == 1'b0) & (ap_predicate_op36_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_predicate_op16_write_state1 = ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (tmp_19_fu_130_p3 == 1'd0));
end

always @ (*) begin
    ap_predicate_op18_write_state1 = ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (tmp_19_fu_130_p3 == 1'd1));
end

always @ (*) begin
    ap_predicate_op26_write_state1 = ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (tmp_20_fu_138_p3 == 1'd0));
end

always @ (*) begin
    ap_predicate_op28_write_state1 = ((tmp_s_nbreadreq_fu_68_p3 == 1'd1) & (tmp_20_fu_138_p3 == 1'd1));
end

always @ (*) begin
    ap_predicate_op36_write_state2 = ((tmp_2_reg_174 == 1'd1) & (tmp_21_fu_146_p3 == 1'd0));
end

always @ (*) begin
    ap_predicate_op38_write_state2 = ((tmp_2_reg_174 == 1'd1) & (tmp_21_fu_146_p3 == 1'd1));
end

always @ (*) begin
    ap_predicate_op46_write_state2 = ((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (tmp_22_fu_154_p3 == 1'd0));
end

always @ (*) begin
    ap_predicate_op48_write_state2 = ((tmp_3_nbreadreq_fu_114_p3 == 1'd1) & (tmp_22_fu_154_p3 == 1'd1));
end

assign tmp_19_fu_130_p3 = lpcore_output_event_stream_0_dout[32'd112];

assign tmp_20_fu_138_p3 = lpcore_cancellation_unit_output_stream_0_dout[32'd112];

assign tmp_21_fu_146_p3 = lpcore_output_event_stream_1_dout[32'd112];

assign tmp_22_fu_154_p3 = lpcore_cancellation_unit_output_stream_1_dout[32'd112];

assign tmp_2_nbreadreq_fu_98_p3 = lpcore_output_event_stream_1_empty_n;

assign tmp_3_nbreadreq_fu_114_p3 = lpcore_cancellation_unit_output_stream_1_empty_n;

assign tmp_nbreadreq_fu_38_p3 = lpcore_output_event_stream_0_empty_n;

assign tmp_s_nbreadreq_fu_68_p3 = lpcore_cancellation_unit_output_stream_0_empty_n;

endmodule //simulation_top_event_router_top
