// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module state_buffer_kernel_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        current_V_2,
        zext_ln1073,
        commit_time_V,
        removed_V_3_out_i,
        removed_V_3_out_o,
        removed_V_3_out_o_ap_vld,
        list_nodes_next_V_address0,
        list_nodes_next_V_ce0,
        list_nodes_next_V_we0,
        list_nodes_next_V_d0,
        list_nodes_next_V_q0,
        list_nodes_state_lvt_V_address0,
        list_nodes_state_lvt_V_ce0,
        list_nodes_state_lvt_V_q0,
        list_free_head_V_i,
        list_free_head_V_o,
        list_free_head_V_o_ap_vld,
        list_lp_sizes_V_address0,
        list_lp_sizes_V_ce0,
        list_lp_sizes_V_we0,
        list_lp_sizes_V_d0,
        list_lp_sizes_V_q0,
        list_lp_heads_V_address0,
        list_lp_heads_V_ce0,
        list_lp_heads_V_we0,
        list_lp_heads_V_d0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] current_V_2;
input  [5:0] zext_ln1073;
input  [31:0] commit_time_V;
input  [15:0] removed_V_3_out_i;
output  [15:0] removed_V_3_out_o;
output   removed_V_3_out_o_ap_vld;
output  [6:0] list_nodes_next_V_address0;
output   list_nodes_next_V_ce0;
output   list_nodes_next_V_we0;
output  [15:0] list_nodes_next_V_d0;
input  [15:0] list_nodes_next_V_q0;
output  [6:0] list_nodes_state_lvt_V_address0;
output   list_nodes_state_lvt_V_ce0;
input  [31:0] list_nodes_state_lvt_V_q0;
input  [15:0] list_free_head_V_i;
output  [15:0] list_free_head_V_o;
output   list_free_head_V_o_ap_vld;
output  [5:0] list_lp_sizes_V_address0;
output   list_lp_sizes_V_ce0;
output   list_lp_sizes_V_we0;
output  [15:0] list_lp_sizes_V_d0;
input  [15:0] list_lp_sizes_V_q0;
output  [5:0] list_lp_heads_V_address0;
output   list_lp_heads_V_ce0;
output   list_lp_heads_V_we0;
output  [15:0] list_lp_heads_V_d0;

reg ap_idle;
reg[15:0] removed_V_3_out_o;
reg removed_V_3_out_o_ap_vld;
reg[6:0] list_nodes_next_V_address0;
reg list_nodes_next_V_ce0;
reg list_nodes_next_V_we0;
reg[15:0] list_nodes_next_V_d0;
reg list_nodes_state_lvt_V_ce0;
reg[15:0] list_free_head_V_o;
reg list_free_head_V_o_ap_vld;
reg list_lp_sizes_V_ce0;
reg list_lp_sizes_V_we0;
reg list_lp_heads_V_ce0;
reg list_lp_heads_V_we0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln1069_fu_162_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state3;
wire    ap_block_state3_pp0_stage2_iter0;
reg   [15:0] current_V_4_reg_286;
reg   [5:0] list_lp_heads_V_addr_reg_292;
reg   [5:0] list_lp_sizes_V_addr_reg_297;
reg   [0:0] icmp_ln1069_reg_302;
reg   [6:0] list_nodes_next_V_addr_reg_306;
reg   [15:0] current_V_5_reg_316;
wire    ap_CS_fsm_state2;
wire    ap_block_state2_pp0_stage1_iter0;
wire   [0:0] or_ln105_fu_182_p2;
reg   [0:0] or_ln105_reg_321;
wire   [63:0] zext_ln1073_cast_fu_138_p1;
wire   [63:0] zext_ln587_fu_168_p1;
wire   [63:0] zext_ln587_1_fu_203_p1;
wire   [0:0] icmp_ln1065_fu_197_p2;
wire   [15:0] removed_V_fu_212_p2;
reg   [0:0] keep_next_fu_48;
wire   [0:0] and_ln105_fu_188_p2;
wire    ap_loop_init;
reg   [15:0] current_V_fu_52;
reg   [15:0] ap_sig_allocacmp_current_V_4;
reg   [15:0] prev_V_fu_56;
wire   [0:0] icmp_ln105_fu_177_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_done_reg = 1'b0;
end

state_buffer_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        current_V_fu_52 <= current_V_2;
    end else if (((icmp_ln1069_reg_302 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        current_V_fu_52 <= current_V_5_reg_316;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        keep_next_fu_48 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (or_ln105_fu_182_p2 == 1'd1))) begin
        keep_next_fu_48 <= and_ln105_fu_188_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (or_ln105_fu_182_p2 == 1'd0))) begin
        keep_next_fu_48 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        prev_V_fu_56 <= 16'd65535;
    end else if (((1'b1 == ap_CS_fsm_state2) & (or_ln105_fu_182_p2 == 1'd1))) begin
        prev_V_fu_56 <= current_V_4_reg_286;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        current_V_4_reg_286 <= ap_sig_allocacmp_current_V_4;
        icmp_ln1069_reg_302 <= icmp_ln1069_fu_162_p2;
        list_lp_heads_V_addr_reg_292 <= zext_ln1073_cast_fu_138_p1;
        list_lp_sizes_V_addr_reg_297 <= zext_ln1073_cast_fu_138_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        current_V_5_reg_316 <= list_nodes_next_V_q0;
        or_ln105_reg_321 <= or_ln105_fu_182_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1069_fu_162_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        list_nodes_next_V_addr_reg_306 <= zext_ln587_fu_168_p1;
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln1069_fu_162_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_V_4 = current_V_2;
    end else begin
        ap_sig_allocacmp_current_V_4 = current_V_fu_52;
    end
end

always @ (*) begin
    if (((icmp_ln1069_reg_302 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (or_ln105_reg_321 == 1'd0))) begin
        list_free_head_V_o = current_V_4_reg_286;
    end else begin
        list_free_head_V_o = list_free_head_V_i;
    end
end

always @ (*) begin
    if (((icmp_ln1069_reg_302 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (or_ln105_reg_321 == 1'd0))) begin
        list_free_head_V_o_ap_vld = 1'b1;
    end else begin
        list_free_head_V_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        list_lp_heads_V_ce0 = 1'b1;
    end else begin
        list_lp_heads_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1065_fu_197_p2 == 1'd1) & (or_ln105_fu_182_p2 == 1'd0))) begin
        list_lp_heads_V_we0 = 1'b1;
    end else begin
        list_lp_heads_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (or_ln105_fu_182_p2 == 1'd0)) | ((icmp_ln1069_reg_302 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (or_ln105_reg_321 == 1'd0)))) begin
        list_lp_sizes_V_ce0 = 1'b1;
    end else begin
        list_lp_sizes_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1069_reg_302 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (or_ln105_reg_321 == 1'd0))) begin
        list_lp_sizes_V_we0 = 1'b1;
    end else begin
        list_lp_sizes_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1069_reg_302 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (or_ln105_reg_321 == 1'd0))) begin
        list_nodes_next_V_address0 = list_nodes_next_V_addr_reg_306;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1065_fu_197_p2 == 1'd0) & (or_ln105_fu_182_p2 == 1'd0))) begin
        list_nodes_next_V_address0 = zext_ln587_1_fu_203_p1;
    end else if (((icmp_ln1069_fu_162_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        list_nodes_next_V_address0 = zext_ln587_fu_168_p1;
    end else begin
        list_nodes_next_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (icmp_ln1065_fu_197_p2 == 1'd0) & (or_ln105_fu_182_p2 == 1'd0)) | ((icmp_ln1069_fu_162_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln1069_reg_302 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (or_ln105_reg_321 == 1'd0)))) begin
        list_nodes_next_V_ce0 = 1'b1;
    end else begin
        list_nodes_next_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1069_reg_302 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (or_ln105_reg_321 == 1'd0))) begin
        list_nodes_next_V_d0 = list_free_head_V_i;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1065_fu_197_p2 == 1'd0) & (or_ln105_fu_182_p2 == 1'd0))) begin
        list_nodes_next_V_d0 = list_nodes_next_V_q0;
    end else begin
        list_nodes_next_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (icmp_ln1065_fu_197_p2 == 1'd0) & (or_ln105_fu_182_p2 == 1'd0)) | ((icmp_ln1069_reg_302 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (or_ln105_reg_321 == 1'd0)))) begin
        list_nodes_next_V_we0 = 1'b1;
    end else begin
        list_nodes_next_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        list_nodes_state_lvt_V_ce0 = 1'b1;
    end else begin
        list_nodes_state_lvt_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (or_ln105_fu_182_p2 == 1'd0))) begin
        removed_V_3_out_o = removed_V_fu_212_p2;
    end else begin
        removed_V_3_out_o = removed_V_3_out_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (or_ln105_fu_182_p2 == 1'd0))) begin
        removed_V_3_out_o_ap_vld = 1'b1;
    end else begin
        removed_V_3_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln1069_fu_162_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln105_fu_188_p2 = (keep_next_fu_48 & icmp_ln105_fu_177_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln105_fu_177_p2 = (($signed(list_nodes_state_lvt_V_q0) > $signed(commit_time_V)) ? 1'b1 : 1'b0);

assign icmp_ln1065_fu_197_p2 = ((prev_V_fu_56 == 16'd65535) ? 1'b1 : 1'b0);

assign icmp_ln1069_fu_162_p2 = ((ap_sig_allocacmp_current_V_4 == 16'd65535) ? 1'b1 : 1'b0);

assign list_lp_heads_V_address0 = list_lp_heads_V_addr_reg_292;

assign list_lp_heads_V_d0 = list_nodes_next_V_q0;

assign list_lp_sizes_V_address0 = list_lp_sizes_V_addr_reg_297;

assign list_lp_sizes_V_d0 = ($signed(list_lp_sizes_V_q0) + $signed(16'd65535));

assign list_nodes_state_lvt_V_address0 = zext_ln587_fu_168_p1;

assign or_ln105_fu_182_p2 = (keep_next_fu_48 | icmp_ln105_fu_177_p2);

assign removed_V_fu_212_p2 = (removed_V_3_out_i + 16'd1);

assign zext_ln1073_cast_fu_138_p1 = zext_ln1073;

assign zext_ln587_1_fu_203_p1 = prev_V_fu_56;

assign zext_ln587_fu_168_p1 = ap_sig_allocacmp_current_V_4;

endmodule //state_buffer_kernel_state_buffer_kernel_Pipeline_VITIS_LOOP_101_2
